
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnrealBuildTool;

public class RpgGameData : ModuleRules
{
	public RpgGameData(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

		this.PublicDefinitions.Add("RPGGAMEDATA_CODEGEN_MAJOR_VERSION=2025");
		this.PublicDefinitions.Add("RPGGAMEDATA_CODEGEN_MINOR_VERSION=4");
		this.PublicDefinitions.Add("RPGGAMEDATA_CODEGEN_PATCH_VERSION=3");

		PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore" });

		PrivateDependencyModuleNames.AddRange(new string[] { "Charon", "JsonUtilities", "Json", });
	}
}


