
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnrealBuildTool;

public class CharonPluginGameEditor : ModuleRules
{
	public CharonPluginGameEditor(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

		PublicDependencyModuleNames.AddRange(new string[] { "Core", "Charon" });

		PrivateDependencyModuleNames.AddRange(new string[] { "CharonEditor", "RpgGameData", "TestData",  "JsonUtilities", "Json", "CoreUObject", "Engine", "UnrealEd", "Slate", "SlateCore", "InputCore", "ToolWidgets",});
	}
}


