
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "Misc/TVariant.h"

/**
  * Enumeration based on int32. Flags, Used in Schemas: NumberTestEntity.
  */
UENUM(BlueprintType, meta = (Bitflags, UseEnumValuesAsMaskValuesInEditor = "true"))
enum class ENumberTestEntityMultiPickList32Bit : uint8 {
		None = 0  UMETA(DisplayName = "None"),
		One = 1  UMETA(DisplayName = "One"),
		Two = 2  UMETA(DisplayName = "Two"),
		Four = 4  UMETA(DisplayName = "Four"),
		Eight = 8  UMETA(DisplayName = "Eight"),
};
ENUM_CLASS_FLAGS(ENumberTestEntityMultiPickList32Bit);

/** Implements variant type traits for enumeration type. */
template<> struct TVariantTraits<ENumberTestEntityMultiPickList32Bit>
{
	static constexpr EVariantTypes GetType() { return EVariantTypes::Enum; }
};
