
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: Test - 0, Used in Schemas: RecursiveEntity.
  */
struct TESTDATA_API ERecursiveEntityId {
public:
	static const FString Test;
	static const FString Test1;
	static const FString Test2;
	static const FString Test3;
	static const FString Test4;
	static const FString Test5;
};
