
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "Misc/TVariant.h"

/**
  * Enumeration based on int32. Default Value: PickValue4 - 0, Flags, Used in Schemas: TestEntity.
  */
UENUM(BlueprintType, meta = (Bitflags, UseEnumValuesAsMaskValuesInEditor = "true"))
enum class ETestEntityMultiPickListField : uint8 {
		None = 0  UMETA(DisplayName = "None"),
		PickValue1 = 1  UMETA(DisplayName = "PickValue1"),
		PickValue2 = 2  UMETA(DisplayName = "PickValue2"),
		PickValue3 = 3  UMETA(DisplayName = "PickValue3"),
		PickValue4 = 4  UMETA(DisplayName = "PickValue4"),
};
ENUM_CLASS_FLAGS(ETestEntityMultiPickListField);

/** Implements variant type traits for enumeration type. */
template<> struct TVariantTraits<ETestEntityMultiPickListField>
{
	static constexpr EVariantTypes GetType() { return EVariantTypes::Enum; }
};
