
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on float. Default Value: UniqueAttributeEntity1 - 0, Used in Schemas: UniqueAttributeEntity.
  */
struct TESTDATA_API EUniqueAttributeEntityNumberKey {
public:
	static const float UniqueAttributeEntity1;
};
