
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "Misc/TVariant.h"

/**
  * Enumeration based on int32. Flags, Used in Schemas: UniqueAttributeEntity.
  */
UENUM(BlueprintType, meta = (Bitflags, UseEnumValuesAsMaskValuesInEditor = "true"))
enum class EUniqueAttributeEntityMultiPickListKey : uint8 {
		None = 0  UMETA(DisplayName = "None"),
		Value = 1  UMETA(DisplayName = "Value"),
		Value2 = 2  UMETA(DisplayName = "Value2"),
};
ENUM_CLASS_FLAGS(EUniqueAttributeEntityMultiPickListKey);

/** Implements variant type traits for enumeration type. */
template<> struct TVariantTraits<EUniqueAttributeEntityMultiPickListKey>
{
	static constexpr EVariantTypes GetType() { return EVariantTypes::Enum; }
};
