
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "Misc/TVariant.h"

/**
  * Enumeration based on int32. Default Value: Option - 0, Used in Schemas: UnionType.
  */
UENUM(BlueprintType)
enum class EUnionTypePickList8 : uint8 {
	None = 0  UMETA(DisplayName = "None"),
	Option = 1  UMETA(DisplayName = "Option"),
};

/** Implements variant type traits for enumeration type. */
template<> struct TVariantTraits<EUnionTypePickList8>
{
	static constexpr EVariantTypes GetType() { return EVariantTypes::Enum; }
};
