
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "Misc/TVariant.h"

/**
  * Enumeration based on int32. Default Value: Options - 0, Flags, Used in Schemas: UnionType.
  */
UENUM(BlueprintType, meta = (Bitflags, UseEnumValuesAsMaskValuesInEditor = "true"))
enum class EUnionTypeMultiPickList9 : uint8 {
		None = 0  UMETA(DisplayName = "None"),
		Options = 1  UMETA(DisplayName = "Options"),
};
ENUM_CLASS_FLAGS(EUnionTypeMultiPickList9);

/** Implements variant type traits for enumeration type. */
template<> struct TVariantTraits<EUnionTypeMultiPickList9>
{
	static constexpr EVariantTypes GetType() { return EVariantTypes::Enum; }
};
