
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "GameData/UGameDataLibrary.h"
#include "JsonObjectWrapper.h"
#include "Misc/EngineVersionComparison.h"

#include "UAllTypesTestVoidFormulaFormula.h"
#include "UAllTypesTestNoParamsFormulaFormula.h"
#include "UAllTypesTestParamsFormulaFormula.h"
#include "UAllTypesTest.generated.h"


/**
  * All Types Test with Text id.
  */
UCLASS(BlueprintType)
class TESTDATA_API UAllTypesTest : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

public:
	/**
	  * Id property of Text type. Not Empty, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Id;
	/**
	  * Asset Path property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString AssetPath;
	/**
	  * Asset Path Collection property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString AssetPathCollection;
	/**
	  * Rectangle property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Rectangle;
	/**
	  * Rectangle property of Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FVector4 GetParsedRectangle() const;
	/**
	  * Vector 2 property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Vector2;
	/**
	  * Vector 2 property of Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FVector2D GetParsedVector2() const;
	/**
	  * Vector 3 property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Vector3;
	/**
	  * Vector 3 property of Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FVector GetParsedVector3() const;
	/**
	  * Vector 4 property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Vector4;
	/**
	  * Vector 4 property of Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FVector4 GetParsedVector4() const;
	/**
	  * Integer Rectangle property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString IntegerRectangle;
	/**
	  * Integer Rectangle property of Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FIntVector4 GetParsedIntegerRectangle() const;
	/**
	  * Integer Vector 2 property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString IntegerVector2;
	/**
	  * Integer Vector 2 property of Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FIntPoint GetParsedIntegerVector2() const;
	/**
	  * Integer Vector 3 property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString IntegerVector3;
	/**
	  * Integer Vector 3 property of Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FIntVector GetParsedIntegerVector3() const;
	/**
	  * Integer Vector 4 property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString IntegerVector4;
	/**
	  * Integer Vector 4 property of Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FIntVector4 GetParsedIntegerVector4() const;
	/**
	  * Tag property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Tag;
	/**
	  * Tag property of Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	TArray<FString> GetParsedTag() const;
	/**
	  * Tag Collection property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString TagCollection;
	/**
	  * Tag Collection property of Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	TArray<FString> GetParsedTagCollection() const;
	/**
	  * Void Formula property of Formula type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	UAllTypesTestVoidFormulaFormula* VoidFormula;
	/**
	  * No Params Formula property of Formula type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	UAllTypesTestNoParamsFormulaFormula* NoParamsFormula;
	/**
	  * Params Formula property of Formula type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	UAllTypesTestParamsFormulaFormula* ParamsFormula;
};
