
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "JsonObjectWrapper.h"

#include "ENumberTestEntityPickList8Bit.h"
#include "ENumberTestEntityPickList16Bit.h"
#include "ENumberTestEntityPickList32Bit.h"
#include "ENumberTestEntityPickList64Bit.h"
#include "ENumberTestEntityMultiPickList8Bit.h"
#include "ENumberTestEntityMultiPickList16Bit.h"
#include "ENumberTestEntityMultiPickList32Bit.h"
#include "ENumberTestEntityMultiPickList64Bit.h"
#include "UNumberTestEntity.generated.h"


/**
  * Number Test Entity with Integer id.
  */
UCLASS(BlueprintType)
class TESTDATA_API UNumberTestEntity : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

public:
	/**
	  * Id property of Integer type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Id;
	/**
	  * Number 32 Bit property of Number type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float Number32Bit;
	/**
	  * Number 64 Bit property of Number type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	double Number64Bit;
	/**
	  * Integer 8 Bit property of Integer type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Integer8Bit;
	/**
	  * Integer 16 Bit property of Integer type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Integer16Bit;
	/**
	  * Integer 32 Bit property of Integer type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Integer32Bit;
	/**
	  * Integer 64 Bit property of Integer type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int64 Integer64Bit;
	/**
	  * Pick List 8 Bit property of Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ENumberTestEntityPickList8Bit PickList8Bit;
	/**
	  * Pick List 16 Bit property of Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ENumberTestEntityPickList16Bit PickList16Bit;
	/**
	  * Pick List 32 Bit property of Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ENumberTestEntityPickList32Bit PickList32Bit;
	/**
	  * Pick List 64 Bit property of Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ENumberTestEntityPickList64Bit PickList64Bit;
	/**
	  * Multi Pick List 8 Bit property of Multi Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ENumberTestEntityMultiPickList8Bit MultiPickList8Bit;
	/**
	  * Multi Pick List 16 Bit property of Multi Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ENumberTestEntityMultiPickList16Bit MultiPickList16Bit;
	/**
	  * Multi Pick List 32 Bit property of Multi Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ENumberTestEntityMultiPickList32Bit MultiPickList32Bit;
	/**
	  * Multi Pick List 64 Bit property of Multi Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ENumberTestEntityMultiPickList64Bit MultiPickList64Bit;
};
