
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UObject/Class.h"
#include "UObject/StrongObjectPtr.h"
#include "UObject/WeakFieldPtr.h"
#include "UObject/UnrealType.h"
#include "Templates/SharedPointer.h"
#include "Dom/JsonObject.h"
#include "JsonObjectWrapper.h"
#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2
#include "GameData/Formulas/Expressions/FFormulaExpression.h"
#include "GameData/Formulas/FExpressionBuildHelper.h"
#include "GameData/Formulas/FFormulaTypeResolver.h"
#include "GameData/Formulas/FFormulaExecutionContext.h"
#include "GameData/Formulas/FFormulaValue.h"
#endif
#if __has_include("UTestDataFormulaTypes.h")
    #include "UTestDataFormulaTypes.h"
#endif
/*
	To use your custom structs/classes in formula parameters, create a file "UTestDataFormulaTypes.h" in this folder, in which you can declare your classes or structs.
*/

DECLARE_LOG_CATEGORY_EXTERN(LogUTestEntityIntFormulaFormula, Log, All);

#include "UTestEntityIntFormulaFormula.generated.h"

/**
  * Formula Signature: (System.Int32 First, int Second) -> int
  */
UCLASS(BlueprintType)
class TESTDATA_API UTestEntityIntFormulaFormula : public UObject
{
	GENERATED_BODY()

private:
#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2
	TSharedPtr<FFormulaExpression> mutable Expression;
#endif
public:
	/**
	  * Gets or sets the Abstract Syntax Tree (AST) of the formula. Used internally.
	  */
	UPROPERTY(VisibleAnywhere)
	FJsonObjectWrapper ExpressionTree;
	/**
	  * Gets or sets the root provider for global identifiers. Properties and methods of this
	  * object can be referenced directly within the formula without a qualifier.
	  */
	UPROPERTY(VisibleAnywhere)
	TObjectPtr<UObject> Global;
	/**
	  * Gets or sets a value indicating whether null propagation should be applied
	  * implicitly to this formula during evaluation or code generation.
	  */
	UPROPERTY(VisibleAnywhere)
	bool AutoNullPropagation;

	/**
	  * Evaluates the formula and returns the resulting value.
	  */
	UFUNCTION(BlueprintCallable)
	int32 Invoke(int32 First, int32 Second) const;

#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2
	/**
	  * Gets original formula expression for custom interpretation.
	  */
	TSharedPtr<FFormulaExpression> GetExpression() const;
#endif
};
