
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UObject/Class.h"
#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "JsonObjectWrapper.h"

#include "UTestEntityFormulaFieldFormula.generated.h"

/**
  * Formula Signature: (System.Int32 arg1, System.Int32 arg2, System.Int32 arg3, System.Int32 arg4) -> System.Int32
  */
UCLASS(BlueprintType)
class TESTDATA_API UTestEntityFormulaFieldFormula : public UObject
{
	GENERATED_BODY()

public:
	UPROPERTY()
	FJsonObjectWrapper ExpressionTree;

	UTestEntityFormulaFieldFormula() { }
};
