
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "GameData/EDocumentReferenceGetResult.h"
#include "UTestDataProjectSettings.h"
#include "UTestEntity.h"
#include "URecursiveEntity.h"
#include "UNumberTestEntity.h"
#include "UUniqueAttributeEntity.h"
#include "UUnionType.h"
#include "ETestEntityPickListField.h"
#include "ETestEntityMultiPickListField.h"
#include "ENumberTestEntityPickList8Bit.h"
#include "ENumberTestEntityPickList16Bit.h"
#include "ENumberTestEntityPickList32Bit.h"
#include "ENumberTestEntityPickList64Bit.h"
#include "ENumberTestEntityMultiPickList8Bit.h"
#include "ENumberTestEntityMultiPickList16Bit.h"
#include "ENumberTestEntityMultiPickList32Bit.h"
#include "ENumberTestEntityMultiPickList64Bit.h"
#include "EUniqueAttributeEntityPickListKey.h"
#include "EUniqueAttributeEntityMultiPickListKey.h"
#include "EUnionTypePickList8.h"
#include "EUnionTypeMultiPickList9.h"
#include "ERecursiveEntityId.h"
#include "ETestEntityId.h"
#include "EUniqueAttributeEntityId.h"
#include "EUniqueAttributeEntitySnakeCaseKey.h"
#include "EUniqueAttributeEntityCamelCaseKey.h"
#include "EUniqueAttributeEntityDromedaryCaseKey.h"
#include "EUniqueAttributeEntityTextKey.h"
#include "EUniqueAttributeEntityNumberKey.h"
#include "EUniqueAttributeEntityIntegerKey.h"
#include "EUniqueAttributeEntityTimeSpanKey.h"
#include "EUniqueAttributeEntityDateTimeKey.h"
#include "UTestEntityFormulaFieldFormula.h"

#include "UTestDataFunctionLibrary.generated.h"

/**
  * Extension functions for generate UTestData class.
  */
UCLASS()
class TESTDATA_API UTestDataFunctionLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

	/*
	 * Get UTestDataProjectSettings referenced in specified DocumentReference.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static UTestDataProjectSettings* GetTestDataProjectSettings(FGameDataDocumentReference DocumentReference, EDocumentReferenceGetResult& Branches)
	{
		UTestDataProjectSettings* Document = Cast<UTestDataProjectSettings>(DocumentReference.GetReferencedDocument());
		if (Document == nullptr)
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
		return Document;
	}
	/*
	 * Get UTestEntity referenced in specified DocumentReference.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static UTestEntity* GetTestEntity(FGameDataDocumentReference DocumentReference, EDocumentReferenceGetResult& Branches)
	{
		UTestEntity* Document = Cast<UTestEntity>(DocumentReference.GetReferencedDocument());
		if (Document == nullptr)
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
		return Document;
	}
	/*
	 * Get URecursiveEntity referenced in specified DocumentReference.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static URecursiveEntity* GetRecursiveEntity(FGameDataDocumentReference DocumentReference, EDocumentReferenceGetResult& Branches)
	{
		URecursiveEntity* Document = Cast<URecursiveEntity>(DocumentReference.GetReferencedDocument());
		if (Document == nullptr)
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
		return Document;
	}
	/*
	 * Get UNumberTestEntity referenced in specified DocumentReference.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static UNumberTestEntity* GetNumberTestEntity(FGameDataDocumentReference DocumentReference, EDocumentReferenceGetResult& Branches)
	{
		UNumberTestEntity* Document = Cast<UNumberTestEntity>(DocumentReference.GetReferencedDocument());
		if (Document == nullptr)
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
		return Document;
	}
	/*
	 * Get UUniqueAttributeEntity referenced in specified DocumentReference.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static UUniqueAttributeEntity* GetUniqueAttributeEntity(FGameDataDocumentReference DocumentReference, EDocumentReferenceGetResult& Branches)
	{
		UUniqueAttributeEntity* Document = Cast<UUniqueAttributeEntity>(DocumentReference.GetReferencedDocument());
		if (Document == nullptr)
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
		return Document;
	}
	/*
	 * Get UUnionType referenced in specified DocumentReference.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static UUnionType* GetUnionType(FGameDataDocumentReference DocumentReference, EDocumentReferenceGetResult& Branches)
	{
		UUnionType* Document = Cast<UUnionType>(DocumentReference.GetReferencedDocument());
		if (Document == nullptr)
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
		return Document;
	}
	/*
	 * Get Text1 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static FString MatchText1(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("Text1"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->Text1;
	}
	/*
	 * Get TextLocalizable2 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static FText MatchTextLocalizable2(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("TextLocalizable2"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->GetTextLocalizable2();
	}
	/*
	 * Get Logical3 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static bool MatchLogical3(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("Logical3"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->Logical3;
	}
	/*
	 * Get Time4 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static FTimespan MatchTime4(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("Time4"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->Time4;
	}
	/*
	 * Get Date5 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static FDateTime MatchDate5(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("Date5"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->Date5;
	}
	/*
	 * Get Number6 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static float MatchNumber6(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("Number6"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->Number6;
	}
	/*
	 * Get NumberInteger7 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static int32 MatchNumberInteger7(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("NumberInteger7"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->NumberInteger7;
	}
	/*
	 * Get PickList8 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static EUnionTypePickList8 MatchPickList8(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("PickList8"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->PickList8;
	}
	/*
	 * Get MultiPickList9 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static EUnionTypeMultiPickList9 MatchMultiPickList9(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("MultiPickList9"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->MultiPickList9;
	}
	/*
	 * Get Document10 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static UNumberTestEntity* MatchDocument10(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("Document10"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->Document10;
	}
	/*
	 * Get CollectionofDocuments11 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static TMap<int32,UNumberTestEntity*> MatchCollectionofDocuments11(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("CollectionofDocuments11"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->CollectionofDocuments11;
	}
	/*
	 * Get Reference12 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static UNumberTestEntity* MatchReference12(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("Reference12"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->GetReference12();
	}
	/*
	 * Get CollectionofReferences13 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static TMap<int32,UNumberTestEntity*> MatchCollectionofReferences13(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("CollectionofReferences13"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->GetCollectionofReferences13();
	}
	/*
	 * Get Formula14 value from specified UUnionType.
	 */
	UFUNCTION(BlueprintCallable, Meta = (ExpandEnumAsExecs = "Branches"))
	static FJsonObjectWrapper MatchFormula14(UUnionType* Document, EDocumentReferenceGetResult& Branches)
	{
		if (Document == nullptr || Document->Tag != TEXT("Formula14"))
		{
			Branches = EDocumentReferenceGetResult::NotFound;
		}
		else
		{
			Branches = EDocumentReferenceGetResult::Found;
		}
			return Document->Formula14;
	}
};
