
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UObject/Class.h"
#include "UObject/StrongObjectPtrTemplates.h"
#include "UObject/WeakFieldPtr.h"
#include "UObject/UnrealType.h"
#include "Templates/SharedPointer.h"
#include "Dom/JsonObject.h"
#include "JsonObjectWrapper.h"
#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2
#include "GameData/Formulas/Expressions/FFormulaExpression.h"
#include "GameData/Formulas/FExpressionBuildHelper.h"
#include "GameData/Formulas/FFormulaTypeResolver.h"
#include "GameData/Formulas/FFormulaExecutionContext.h"
#include "GameData/Formulas/FFormulaValue.h"
#endif
#if __has_include("UTestDataFormulaTypes.h")
    #include "UTestDataFormulaTypes.h"
#endif

DECLARE_LOG_CATEGORY_EXTERN(LogUTestEntityFormulaFieldFormula, Log, All);

#include "UTestEntityFormulaFieldFormula.generated.h"

/**
  * Formula Signature: (System.Int32 arg1, System.Int32 arg2, System.Int32 arg3, System.Int32 arg4) -> System.Int32
  */
UCLASS(BlueprintType)
class TESTDATA_API UTestEntityFormulaFieldFormula : public UObject
{
	GENERATED_BODY()

private:
#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2
	TSharedPtr<FFormulaExpression> mutable Expression;
#endif
public:
	/**
	  * Gets or sets the Abstract Syntax Tree (AST) of the formula. Used internally.
	  */
	UPROPERTY()
	FJsonObjectWrapper ExpressionTree;
	/**
	  * Gets or sets the root provider for global identifiers. Properties and methods of this
	  * object can be referenced directly within the formula without a qualifier.
	  */
	UPROPERTY()
	TObjectPtr<UObject> Global;
	/**
	  * Gets or sets a value indicating whether null propagation should be applied
	  * implicitly to this formula during evaluation or code generation.
	  */
	UPROPERTY()
	bool AutoNullPropagation;

	/**
	  * Evaluates the formula and returns the resulting value.
	  */
	UFUNCTION()
	int32 Invoke(int32 Arg1, int32 Arg2, int32 Arg3, int32 Arg4) const;

#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2
	/**
	  * Gets original formula expression for custom interpretation.
	  */
	TSharedPtr<FFormulaExpression> GetExpression() const;
#endif
};
