
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "JsonObjectWrapper.h"

#include "ETestEntityPickListField.h"
#include "ETestEntityMultiPickListField.h"
#include "UTestEntityFormulaFieldFormula.h"
#include "UTestEntity.generated.h"

class UUnionType; // forward declaration

/**
  * This is test description.
  */
UCLASS(BlueprintType)
class TESTDATA_API UTestEntity : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

	/**
	  * De-referenced document of ReferenceField. Should not be directly used.
	  */
	UTestEntity* _referenceFieldDocument;
	/**
	  * De-referenced collection of documents for ListOfReferencesField. Should not be directly used.
	  */
	TMap<FString,UTestEntity*> _listOfReferencesFieldDocuments;
public:
	/**
	  * Id property of Text type. Not Empty, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Id;
	/**
	  * Text Field property of Text type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString TextField;
	/**
	  * Localized Text Field property of Localized Text type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	FText GetLocalizedTextField();
	/**
	  * Raw value of LocalizedTextField.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FLocalizedText LocalizedTextFieldRaw;
	/**
	  * Logical Field property of Logical type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	bool LogicalField;
	/**
	  * Time Field property of Time type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FTimespan TimeField;
	/**
	  * Date Field property of Date type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FDateTime DateField;
	/**
	  * Number Field property of Number type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float NumberField;
	/**
	  * Number Field X64 property of Number type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	double NumberFieldX64;
	/**
	  * Integer Field property of Integer type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 IntegerField;
	/**
	  * Integer Field X64 property of Integer type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int64 IntegerFieldX64;
	/**
	  * Pick List Field property of Pick List type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ETestEntityPickListField PickListField;
	/**
	  * Multi Pick List Field property of Multi Pick List type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ETestEntityMultiPickListField MultiPickListField;
	/**
	  * Document Field property of Document type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	UTestEntity* DocumentField;
	/**
	  * List Of Documents Field property of Document Collection type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<FString,UTestEntity*> ListOfDocumentsField;
	/**
	  * Reference Field property of Reference type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	UTestEntity* GetReferenceField();
	/**
	  * Raw value of ReferenceField.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference ReferenceFieldRaw;
	/**
	  * List Of References Field property of Reference Collection type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	TMap<FString,UTestEntity*> GetListOfReferencesField();
	/**
	  * Raw value of ListOfReferencesField.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TArray<FGameDataDocumentReference> ListOfReferencesFieldRaw;
	/**
	  * Formula Field property of Formula type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	UTestEntityFormulaFieldFormula* FormulaField;
	/**
	  * Is Published property of Logical type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	bool IsPublished;
	/**
	  * Union Field property of Document Collection type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<int32,UUnionType*> UnionField;
};
