
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"

#include "EUniqueAttributeEntityPickListKey.h"
#include "EUniqueAttributeEntityMultiPickListKey.h"
#include "UUniqueAttributeEntity.generated.h"


/**
  * Unique Attribute Entity with Text id. Unique Properties: Id, SnakeCaseKey, CamelCaseKey, DromedaryCaseKey, TextKey, NonRequiredKey, NumberKey, IntegerKey, PickListKey, MultiPickListKey, TimeSpanKey, DateTimeKey.
  */
UCLASS(BlueprintType)
class TESTDATA_API UUniqueAttributeEntity : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

public:
	/**
	  * Id property of Text type. Not Empty, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Id;
	/**
	  * lower case key property of Text type. Can Be Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString SnakeCaseKey;
	/**
	  * camel Case Key property of Text type. Can Be Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString CamelCaseKey;
	/**
	  * Dromedary Case Key property of Text type. Can Be Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString DromedaryCaseKey;
	/**
	  * Text Key property of Text type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString TextKey;
	/**
	  * Non Required Key property of Text type. Can Be Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString NonRequiredKey;
	/**
	  * Number Key property of Number type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float NumberKey;
	/**
	  * Integer Key property of Integer type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 IntegerKey;
	/**
	  * Pick List Key property of Pick List type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	EUniqueAttributeEntityPickListKey PickListKey;
	/**
	  * Multi Pick List Key property of Multi Pick List type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	EUniqueAttributeEntityMultiPickListKey MultiPickListKey;
	/**
	  * Time Key property of Time type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FTimespan TimeSpanKey;
	/**
	  * Date Key property of Date type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FDateTime DateTimeKey;
};
