
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "JsonObjectWrapper.h"

#include "EUnionTypePickList8.h"
#include "EUnionTypeMultiPickList9.h"
#include "UUnionType.generated.h"

class UNumberTestEntity; // forward declaration

/**
  * Union Type with Integer id.
  */
UCLASS(BlueprintType)
class TESTDATA_API UUnionType : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

	/**
	  * De-referenced document of Reference12. Should not be directly used.
	  */
	UNumberTestEntity* _reference12Document;
	/**
	  * De-referenced collection of documents for CollectionofReferences13. Should not be directly used.
	  */
	TMap<int32,UNumberTestEntity*> _collectionofReferences13Documents;
public:
	/**
	  * Id property of Integer type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Id;
	/**
	  * Text 1 property of Text type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Text1;
	/**
	  * Text Localizable 2 property of Localized Text type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	FText GetTextLocalizable2();
	/**
	  * Raw value of TextLocalizable2.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FLocalizedText TextLocalizable2Raw;
	/**
	  * Logical 3 property of Logical type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	bool Logical3;
	/**
	  * Time 4 property of Time type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FTimespan Time4;
	/**
	  * Date 5 property of Date type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FDateTime Date5;
	/**
	  * Number 6 property of Number type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float Number6;
	/**
	  * Number Integer 7 property of Integer type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 NumberInteger7;
	/**
	  * Pick List 8 property of Pick List type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	EUnionTypePickList8 PickList8;
	/**
	  * Multi Pick List 9 property of Multi Pick List type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	EUnionTypeMultiPickList9 MultiPickList9;
	/**
	  * Document 10 property of Document type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	UNumberTestEntity* Document10;
	/**
	  * Collectionof Documents 11 property of Document Collection type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<int32,UNumberTestEntity*> CollectionofDocuments11;
	/**
	  * Reference 12 property of Reference type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	UNumberTestEntity* GetReference12();
	/**
	  * Raw value of Reference12.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference Reference12Raw;
	/**
	  * Collectionof References 13 property of Reference Collection type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	TMap<int32,UNumberTestEntity*> GetCollectionofReferences13();
	/**
	  * Raw value of CollectionofReferences13.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TArray<FGameDataDocumentReference> CollectionofReferences13Raw;
	/**
	  * Formula 14 property of Formula type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FJsonObjectWrapper Formula14;

	/**
	  * The name of the selected property in a tagged union.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Tag;

	/**
	  *  / Visitor interface for processing tagged union variants in a type-safe manner.
	  */
	struct FUnionVisitor
	{
	public:
		virtual ~FUnionVisitor() = default;
		/**
		  *  Visits the Text1 variant.
		  */
		virtual void VisitText1(FString Text1);
		/**
		  *  Visits the TextLocalizable2 variant.
		  */
		virtual void VisitTextLocalizable2(FText TextLocalizable2);
		/**
		  *  Visits the Logical3 variant.
		  */
		virtual void VisitLogical3(bool Logical3);
		/**
		  *  Visits the Time4 variant.
		  */
		virtual void VisitTime4(FTimespan Time4);
		/**
		  *  Visits the Date5 variant.
		  */
		virtual void VisitDate5(FDateTime Date5);
		/**
		  *  Visits the Number6 variant.
		  */
		virtual void VisitNumber6(float Number6);
		/**
		  *  Visits the NumberInteger7 variant.
		  */
		virtual void VisitNumberInteger7(int32 NumberInteger7);
		/**
		  *  Visits the PickList8 variant.
		  */
		virtual void VisitPickList8(EUnionTypePickList8 PickList8);
		/**
		  *  Visits the MultiPickList9 variant.
		  */
		virtual void VisitMultiPickList9(EUnionTypeMultiPickList9 MultiPickList9);
		/**
		  *  Visits the Document10 variant.
		  */
		virtual void VisitDocument10(UNumberTestEntity* Document10);
		/**
		  *  Visits the CollectionofDocuments11 variant.
		  */
		virtual void VisitCollectionofDocuments11(TMap<int32,UNumberTestEntity*> CollectionofDocuments11);
		/**
		  *  Visits the Reference12 variant.
		  */
		virtual void VisitReference12(UNumberTestEntity* Reference12);
		/**
		  *  Visits the CollectionofReferences13 variant.
		  */
		virtual void VisitCollectionofReferences13(TMap<int32,UNumberTestEntity*> CollectionofReferences13);
		/**
		  *  Visits the Formula14 variant.
		  */
		virtual void VisitFormula14(FJsonObjectWrapper Formula14);

		/**
		  *  Visits the empty union or unknown tag.
		  */
		virtual void UnknownTag(FString Tag);
	};

	/**
	  * Applies a visitor to this tagged union, executing the appropriate visit method based on the active variant.
	  */
	void Apply(FUnionVisitor& visitor);
};
