
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EArmorId.h"

// ReSharper disable All
const FString EArmorId::CrossbowerArmor1 = TEXT("CrossbowerArmor1");
const FString EArmorId::CrossbowerArmor2 = TEXT("CrossbowerArmor2");
const FString EArmorId::CrossbowerArmor3 = TEXT("CrossbowerArmor3");
const FString EArmorId::CrossbowerArmor4 = TEXT("CrossbowerArmor4");
const FString EArmorId::CrossbowerArmor5 = TEXT("CrossbowerArmor5");
const FString EArmorId::MonstrosityArmor1 = TEXT("MonstrosityArmor1");
const FString EArmorId::MonstrosityArmor2 = TEXT("MonstrosityArmor2");
const FString EArmorId::MonstrosityArmor3 = TEXT("MonstrosityArmor3");
const FString EArmorId::MonstrosityArmor4 = TEXT("MonstrosityArmor4");
const FString EArmorId::MonstrosityArmor5 = TEXT("MonstrosityArmor5");
const FString EArmorId::ZealotArmor1 = TEXT("ZealotArmor1");
const FString EArmorId::ZealotArmor2 = TEXT("ZealotArmor2");
const FString EArmorId::ZealotArmor3 = TEXT("ZealotArmor3");
const FString EArmorId::ZealotArmor4 = TEXT("ZealotArmor4");
const FString EArmorId::ZealotArmor5 = TEXT("ZealotArmor5");
