
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EConditionsId.h"

// ReSharper disable All
const FString EConditionsId::AboveDimLight = TEXT("AboveDimLight");
const FString EConditionsId::Dark = TEXT("Dark");
const FString EConditionsId::FirstRound = TEXT("FirstRound");
const FString EConditionsId::LocationHarbor = TEXT("LocationHarbor");
const FString EConditionsId::LocationLabyrinth = TEXT("LocationLabyrinth");
const FString EConditionsId::LocationRuins = TEXT("LocationRuins");
const FString EConditionsId::LocationWoodland = TEXT("LocationWoodland");
const FString EConditionsId::LowHealth = TEXT("LowHealth");
const FString EConditionsId::MeleeAttack = TEXT("MeleeAttack");
const FString EConditionsId::MonsterTypeBeast = TEXT("MonsterTypeBeast");
const FString EConditionsId::MonsterTypeCorpse = TEXT("MonsterTypeCorpse");
const FString EConditionsId::MonsterTypeEldritch = TEXT("MonsterTypeEldritch");
const FString EConditionsId::MonsterTypeHuman = TEXT("MonsterTypeHuman");
const FString EConditionsId::MonsterTypeUnholy = TEXT("MonsterTypeUnholy");
const FString EConditionsId::RadiantLight = TEXT("RadiantLight");
const FString EConditionsId::RangedAttack = TEXT("RangedAttack");
const FString EConditionsId::Shadowy = TEXT("Shadowy");
const FString EConditionsId::Stressed = TEXT("Stressed");
