
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "ECurioId.h"

// ReSharper disable All
const FString ECurioId::Crate = TEXT("Crate");
const FString ECurioId::EldritchAltar = TEXT("EldritchAltar");
const FString ECurioId::LockedSarcophagus = TEXT("LockedSarcophagus");
const FString ECurioId::MeatCart = TEXT("MeatCart");
const FString ECurioId::Sconce = TEXT("Sconce");
