
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EDiseaseId.h"

// ReSharper disable All
const FString EDiseaseId::BadHumors = TEXT("BadHumors");
const FString EDiseaseId::CreepingCough = TEXT("CreepingCough");
const FString EDiseaseId::Ennui = TEXT("Ennui");
const FString EDiseaseId::Hemophilia = TEXT("Hemophilia");
const FString EDiseaseId::Rabies = TEXT("Rabies");
const FString EDiseaseId::TheRuns = TEXT("TheRuns");
