
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EHeroId.h"

// ReSharper disable All
const FString EHeroId::Crossbower = TEXT("Crossbower");
const FString EHeroId::Monstrosity = TEXT("Monstrosity");
const FString EHeroId::Zealot = TEXT("Zealot");
