
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EItemId.h"

// ReSharper disable All
const FString EItemId::AccuracyStone = TEXT("AccuracyStone");
const FString EItemId::AncestorsRelic = TEXT("AncestorsRelic");
const FString EItemId::Antivenom = TEXT("Antivenom");
const FString EItemId::Bandage = TEXT("Bandage");
const FString EItemId::BeastSlayersRing = TEXT("BeastSlayersRing");
const FString EItemId::Bust = TEXT("Bust");
const FString EItemId::CautionCloak = TEXT("CautionCloak");
const FString EItemId::Citrine = TEXT("Citrine");
const FString EItemId::Crest = TEXT("Crest");
const FString EItemId::DarkBracer = TEXT("DarkBracer");
const FString EItemId::Deed = TEXT("Deed");
const FString EItemId::DogTreats = TEXT("DogTreats");
const FString EItemId::Emerald = TEXT("Emerald");
const FString EItemId::Firewood = TEXT("Firewood");
const FString EItemId::Food = TEXT("Food");
const FString EItemId::Gold = TEXT("Gold");
const FString EItemId::GrainSack = TEXT("GrainSack");
const FString EItemId::HandofGlory = TEXT("HandofGlory");
const FString EItemId::HerbalRemedies = TEXT("HerbalRemedies");
const FString EItemId::HerosRing = TEXT("HerosRing");
const FString EItemId::HolyRelic = TEXT("HolyRelic");
const FString EItemId::HolyWater = TEXT("HolyWater");
const FString EItemId::Jade = TEXT("Jade");
const FString EItemId::JuteTapestry = TEXT("JuteTapestry");
const FString EItemId::Medicine = TEXT("Medicine");
const FString EItemId::MinorAntique = TEXT("MinorAntique");
const FString EItemId::Onyx = TEXT("Onyx");
const FString EItemId::PickAxe = TEXT("PickAxe");
const FString EItemId::PinealGland = TEXT("PinealGland");
const FString EItemId::Portrait = TEXT("Portrait");
const FString EItemId::PotentSalve = TEXT("PotentSalve");
const FString EItemId::ProtectivePadlock = TEXT("ProtectivePadlock");
const FString EItemId::PuzzlingTrapezohedron = TEXT("PuzzlingTrapezohedron");
const FString EItemId::RareAntique = TEXT("RareAntique");
const FString EItemId::Ruby = TEXT("Ruby");
const FString EItemId::Sapphire = TEXT("Sapphire");
const FString EItemId::Shovel = TEXT("Shovel");
const FString EItemId::SkeletonKey = TEXT("SkeletonKey");
const FString EItemId::Torch = TEXT("Torch");
