
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "ELocationId.h"

// ReSharper disable All
const FString ELocationId::Harbor = TEXT("Harbor");
const FString ELocationId::Labyrinth = TEXT("Labyrinth");
const FString ELocationId::Ruins = TEXT("Ruins");
const FString ELocationId::TheDarkCavern = TEXT("TheDarkCavern");
const FString ELocationId::TheOldRoad = TEXT("TheOldRoad");
const FString ELocationId::TheVillage = TEXT("TheVillage");
const FString ELocationId::Woodland = TEXT("Woodland");
