
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EMonsterId.h"

// ReSharper disable All
const FString EMonsterId::BoneCourtier = TEXT("BoneCourtier");
const FString EMonsterId::BoneSoldier = TEXT("BoneSoldier");
const FString EMonsterId::CultistAcolyte = TEXT("CultistAcolyte");
const FString EMonsterId::CultistFighter = TEXT("CultistFighter");
const FString EMonsterId::PorkChopper = TEXT("PorkChopper");
const FString EMonsterId::PorkWretch = TEXT("PorkWretch");
