
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EProvisionId.h"

// ReSharper disable All
const FString EProvisionId::Antivenom = TEXT("Antivenom");
const FString EProvisionId::Bandage = TEXT("Bandage");
const FString EProvisionId::DogTreats = TEXT("DogTreats");
const FString EProvisionId::Firewood = TEXT("Firewood");
const FString EProvisionId::Food = TEXT("Food");
const FString EProvisionId::HerbalRemedies = TEXT("HerbalRemedies");
const FString EProvisionId::HolyWater = TEXT("HolyWater");
const FString EProvisionId::Shovel = TEXT("Shovel");
const FString EProvisionId::SkeletonKey = TEXT("SkeletonKey");
const FString EProvisionId::Torch = TEXT("Torch");
