
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EQuirkId.h"

// ReSharper disable All
const FString EQuirkId::Anemic = TEXT("Anemic");
const FString EQuirkId::BeastHater = TEXT("BeastHater");
const FString EQuirkId::Clotter = TEXT("Clotter");
const FString EQuirkId::Clumsy = TEXT("Clumsy");
const FString EQuirkId::Evasive = TEXT("Evasive");
const FString EQuirkId::FearOfBeasts = TEXT("FearOfBeasts");
const FString EQuirkId::HarborAdventurer = TEXT("HarborAdventurer");
const FString EQuirkId::HarborPhobe = TEXT("HarborPhobe");
