
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "ETrinketId.h"

// ReSharper disable All
const FString ETrinketId::AccuracyStone = TEXT("AccuracyStone");
const FString ETrinketId::BeastSlayersRing = TEXT("BeastSlayersRing");
const FString ETrinketId::CautionCloak = TEXT("CautionCloak");
const FString ETrinketId::DarkBracer = TEXT("DarkBracer");
const FString ETrinketId::HerosRing = TEXT("HerosRing");
const FString ETrinketId::ProtectivePadlock = TEXT("ProtectivePadlock");
