
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EWeaponId.h"

// ReSharper disable All
const FString EWeaponId::CrossbowerWeapon1 = TEXT("CrossbowerWeapon1");
const FString EWeaponId::CrossbowerWeapon2 = TEXT("CrossbowerWeapon2");
const FString EWeaponId::CrossbowerWeapon3 = TEXT("CrossbowerWeapon3");
const FString EWeaponId::CrossbowerWeapon4 = TEXT("CrossbowerWeapon4");
const FString EWeaponId::CrossbowerWeapon5 = TEXT("CrossbowerWeapon5");
const FString EWeaponId::MonstrosityWeapon1 = TEXT("MonstrosityWeapon1");
const FString EWeaponId::MonstrosityWeapon2 = TEXT("MonstrosityWeapon2");
const FString EWeaponId::MonstrosityWeapon3 = TEXT("MonstrosityWeapon3");
const FString EWeaponId::MonstrosityWeapon4 = TEXT("MonstrosityWeapon4");
const FString EWeaponId::MonstrosityWeapon5 = TEXT("MonstrosityWeapon5");
const FString EWeaponId::ZealotWeapon1 = TEXT("ZealotWeapon1");
const FString EWeaponId::ZealotWeapon2 = TEXT("ZealotWeapon2");
const FString EWeaponId::ZealotWeapon3 = TEXT("ZealotWeapon3");
const FString EWeaponId::ZealotWeapon4 = TEXT("ZealotWeapon4");
const FString EWeaponId::ZealotWeapon5 = TEXT("ZealotWeapon5");
