
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UArmor.h"

const FString UArmor::SchemaId = TEXT("59f9e7b6983a364298db5e2c");
const FString UArmor::SchemaName = TEXT("Armor");

FText UArmor::GetName() {
	return NameRaw.GetCurrent();
}
