
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UCombatEffect.h"
#include "UParameterValue.h"

const FString UCombatEffect::SchemaId = TEXT("59f5baaa30bb84165c06b5a0");
const FString UCombatEffect::SchemaName = TEXT("CombatEffect");

