
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UCondition.h"
#include "UConditionsCheckFormula.h"

const FString UCondition::SchemaId = TEXT("59f5dedf983a361970003697");
const FString UCondition::SchemaName = TEXT("Conditions");

FText UCondition::GetDescription() {
	return DescriptionRaw.GetCurrent();
}
