
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UCurio.h"
#include "UCurioCleansingOption.h"
#include "ULocation.h"

const FString UCurio::SchemaId = TEXT("59f5bbc230bb84165c06b5ae");
const FString UCurio::SchemaName = TEXT("Curio");

FText UCurio::GetName() const {
	return NameRaw.GetCurrent();
}
FText UCurio::GetDescription() const {
	return DescriptionRaw.GetCurrent();
}
TMap<FString,ULocation*> UCurio::GetLocations() const {
	FGameDataDocumentReference::GetReferencedDocuments(LocationsRaw, _LocationsDocuments);
	return _LocationsDocuments;
}
