
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UCurioCleansingOption.h"
#include "UItem.h"
#include "ULoot.h"
#include "UParameterValue.h"

const FString UCurioCleansingOption::SchemaId = TEXT("59f5bac130bb84165c06b5a4");
const FString UCurioCleansingOption::SchemaName = TEXT("CurioCleansingOption");

UItem* UCurioCleansingOption::GetItem() {
		FGameDataDocumentReference::GetReferencedDocument(ItemRaw, _itemDocument);
		return _itemDocument;
}
