
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UDisease.h"
#include "UParameterValue.h"

const FString UDisease::SchemaId = TEXT("59f5d3a7983a361970003662");
const FString UDisease::SchemaName = TEXT("Disease");

FText UDisease::GetName() {
	return NameRaw.GetCurrent();
}
