
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UHero.h"
#include "UProvision.h"
#include "UArmor.h"
#include "UWeapon.h"

const FString UHero::SchemaId = TEXT("59f5b29330bb84165c06b55c");
const FString UHero::SchemaName = TEXT("Hero");

FText UHero::GetName() {
	return NameRaw.GetCurrent();
}
FText UHero::GetBio() {
	return BioRaw.GetCurrent();
}
TMap<FString,UHero*> UHero::GetDislikeHeroes() {
	FGameDataDocumentReference::GetReferencedDocuments(DislikeHeroesRaw, _dislikeHeroesDocuments);
	return _dislikeHeroesDocuments;
}
UProvision* UHero::GetProvisions() {
		FGameDataDocumentReference::GetReferencedDocument(ProvisionsRaw, _provisionsDocument);
		return _provisionsDocument;
}
