
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UItemWithCount.h"
#include "UItem.h"

const FString UItemWithCount::SchemaId = TEXT("5a1d78d107ff9a7b889cba7d");
const FString UItemWithCount::SchemaName = TEXT("ItemWithCount");

UItem* UItemWithCount::GetItem() {
		FGameDataDocumentReference::GetReferencedDocument(ItemRaw, _itemDocument);
		return _itemDocument;
}
