
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UItem.h"
#include "UParameterValue.h"

const FString UItem::SchemaId = TEXT("59f5b3f130bb84165c06b56b");
const FString UItem::SchemaName = TEXT("Item");

FText UItem::GetName() {
	return NameRaw.GetCurrent();
}
FText UItem::GetDescription() {
	return DescriptionRaw.GetCurrent();
}
