
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "ULocation.h"

const FString ULocation::SchemaId = TEXT("59f5b57530bb84165c06b579");
const FString ULocation::SchemaName = TEXT("Location");

FText ULocation::GetName() {
	return NameRaw.GetCurrent();
}
