
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "ULoot.h"

const FString ULoot::SchemaId = TEXT("59f5b9dd30bb84165c06b59a");
const FString ULoot::SchemaName = TEXT("Loot");

