
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UMonster.h"
#include "UParameterValue.h"
#include "ULocation.h"

const FString UMonster::SchemaId = TEXT("59f5b7f330bb84165c06b58a");
const FString UMonster::SchemaName = TEXT("Monster");

FText UMonster::GetName() {
	return NameRaw.GetCurrent();
}
TMap<FString,ULocation*> UMonster::GetLocations() {
	FGameDataDocumentReference::GetReferencedDocuments(LocationsRaw, _locationsDocuments);
	return _locationsDocuments;
}
