
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UParameterValue.h"
#include "UParameter.h"
#include "UCondition.h"

const FString UParameterValue::SchemaId = TEXT("59f5b11030bb84165c06b54e");
const FString UParameterValue::SchemaName = TEXT("ParameterValue");

UParameter* UParameterValue::GetParameter() {
		FGameDataDocumentReference::GetReferencedDocument(ParameterRaw, _parameterDocument);
		return _parameterDocument;
}
UCondition* UParameterValue::GetCondition() {
		FGameDataDocumentReference::GetReferencedDocument(ConditionRaw, _conditionDocument);
		return _conditionDocument;
}
