
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UParameter.h"

const FString UParameter::SchemaId = TEXT("59f5b0a730bb84165c06b547");
const FString UParameter::SchemaName = TEXT("Parameter");

UParameter* UParameter::GetMinValueParameter() const {
	FGameDataDocumentReference::GetReferencedDocument(MinValueParameterRaw, _MinValueParameterDocument);
	return _MinValueParameterDocument;
}
UParameter* UParameter::GetMaxValueParameter() const {
	FGameDataDocumentReference::GetReferencedDocument(MaxValueParameterRaw, _MaxValueParameterDocument);
	return _MaxValueParameterDocument;
}
