
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UParameter.h"

const FString UParameter::SchemaId = TEXT("59f5b0a730bb84165c06b547");
const FString UParameter::SchemaName = TEXT("Parameter");

UParameter* UParameter::GetMinValueParameter() {
		FGameDataDocumentReference::GetReferencedDocument(MinValueParameterRaw, _minValueParameterDocument);
		return _minValueParameterDocument;
}
UParameter* UParameter::GetMaxValueParameter() {
		FGameDataDocumentReference::GetReferencedDocument(MaxValueParameterRaw, _maxValueParameterDocument);
		return _maxValueParameterDocument;
}
