
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UProvision.h"
#include "UItem.h"

const FString UProvision::SchemaId = TEXT("59f5b1c830bb84165c06b556");
const FString UProvision::SchemaName = TEXT("Provision");

