
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UQuirk.h"
#include "UParameterValue.h"

const FString UQuirk::SchemaId = TEXT("59f5d728983a361970003684");
const FString UQuirk::SchemaName = TEXT("Quirk");

FText UQuirk::GetName() {
	return NameRaw.GetCurrent();
}
