
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UStartingSet.h"
#include "UItemWithCount.h"
#include "UHero.h"
#include "ULocation.h"

const FString UStartingSet::SchemaId = TEXT("5a1d78de07ff9a7b889cba83");
const FString UStartingSet::SchemaName = TEXT("StartingSet");

TMap<FString,UHero*> UStartingSet::GetHeroes() {
	FGameDataDocumentReference::GetReferencedDocuments(HeroesRaw, _heroesDocuments);
	return _heroesDocuments;
}
ULocation* UStartingSet::GetLocation() {
		FGameDataDocumentReference::GetReferencedDocument(LocationRaw, _locationDocument);
		return _locationDocument;
}
