
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UTrinket.h"
#include "ULocation.h"
#include "UHero.h"
#include "UItem.h"
#include "UParameterValue.h"

const FString UTrinket::SchemaId = TEXT("59f5b61630bb84165c06b57f");
const FString UTrinket::SchemaName = TEXT("Trinket");

ULocation* UTrinket::GetOriginDungeon() {
		FGameDataDocumentReference::GetReferencedDocument(OriginDungeonRaw, _originDungeonDocument);
		return _originDungeonDocument;
}
UHero* UTrinket::GetHeroRestriction() {
		FGameDataDocumentReference::GetReferencedDocument(HeroRestrictionRaw, _heroRestrictionDocument);
		return _heroRestrictionDocument;
}
