
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UWeapon.h"

const FString UWeapon::SchemaId = TEXT("59f9e745983a364298db5e22");
const FString UWeapon::SchemaName = TEXT("Weapon");

FText UWeapon::GetName() {
	return NameRaw.GetCurrent();
}
