
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "ETestEntityId.h"

// ReSharper disable All
const FString ETestEntityId::TestEntity1 = TEXT("TestEntity1");
const FString ETestEntityId::TestEntity2 = TEXT("TestEntity2");
const FString ETestEntityId::TestEntity3 = TEXT("TestEntity3");
