
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EUniqueAttributeEntityTimeSpanKey.h"

// ReSharper disable All
const FTimespan EUniqueAttributeEntityTimeSpanKey::UniqueAttributeEntity1 = []() { FTimespan Result; FTimespan::Parse(TEXT("01:00:00"), Result); return Result; }();;
