
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EUniqueAttributeEntityNumberKey.h"

// ReSharper disable All
const float EUniqueAttributeEntityNumberKey::UniqueAttributeEntity1 = 1.2;
