
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "EUniqueAttributeEntityDateTimeKey.h"

// ReSharper disable All
const FDateTime EUniqueAttributeEntityDateTimeKey::UniqueAttributeEntity1 = []() { FDateTime Result; FDateTime::ParseIso8601(TEXT("1970-07-10T00:00:00.000Z"), Result); return Result; }();;
