
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UAllTypesTest.h"
#include "UAllTypesTestVoidFormulaFormula.h"
#include "UAllTypesTestNoParamsFormulaFormula.h"
#include "UAllTypesTestParamsFormulaFormula.h"

const FString UAllTypesTest::SchemaId = TEXT("697fa0a4ecd20b7208b73d2d");
const FString UAllTypesTest::SchemaName = TEXT("AllTypesTest");

FVector4 UAllTypesTest::GetParsedRectangle() const
{
	return UGameDataLibrary::ParseVector4(this->Rectangle);
}
FVector2D UAllTypesTest::GetParsedVector2() const
{
	return UGameDataLibrary::ParseVector2(this->Vector2);
}
FVector UAllTypesTest::GetParsedVector3() const
{
	return UGameDataLibrary::ParseVector3(this->Vector3);
}
FVector4 UAllTypesTest::GetParsedVector4() const
{
	return UGameDataLibrary::ParseVector4(this->Vector4);
}
FIntVector4 UAllTypesTest::GetParsedIntegerRectangle() const
{
	return UGameDataLibrary::ParseIntVector4(this->IntegerRectangle);
}
FIntPoint UAllTypesTest::GetParsedIntegerVector2() const
{
	return UGameDataLibrary::ParseFIntPoint(this->IntegerVector2);
}
FIntVector UAllTypesTest::GetParsedIntegerVector3() const
{
	return UGameDataLibrary::ParseIntVector3(this->IntegerVector3);
}
FIntVector4 UAllTypesTest::GetParsedIntegerVector4() const
{
	return UGameDataLibrary::ParseIntVector4(this->IntegerVector4);
}
TArray<FString> UAllTypesTest::GetParsedTag() const
{
	return UGameDataLibrary::ParseTags(this->Tag);
}
TArray<FString> UAllTypesTest::GetParsedTagCollection() const
{
	return UGameDataLibrary::ParseTags(this->TagCollection);
}
