
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UAllTypesTestParamsFormulaFormula.h"
#include "UTestData.h"

DEFINE_LOG_CATEGORY(LogUAllTypesTestParamsFormulaFormula);

#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2

static TSharedRef<FFormulaTypeResolver> UAllTypesTestParamsFormulaFormula_GetOrCreateTypeResolver()
{
	static TSharedRef<FFormulaTypeResolver> __TypeResolver = MakeShared<FFormulaTypeResolver>(UTestData::GetSharedFormulaTypeResolver(), TArray<UObject*> {
		UObject::StaticClass(),
	});

	return __TypeResolver;
}

static UFunction* UAllTypesTestParamsFormulaFormula_GetInvokeFunction()
{
	static TWeakObjectPtr<UFunction> InvokeFunction = UAllTypesTestParamsFormulaFormula::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UAllTypesTestParamsFormulaFormula, Invoke));

	if (!InvokeFunction.IsValid())
	{
		UE_LOG(LogUAllTypesTestParamsFormulaFormula, Error, TEXT("Failed to find required 'Invoke' function on 'UAllTypesTestParamsFormulaFormula' type."));
	}
	return InvokeFunction.Get();
}

static FProperty* UAllTypesTestParamsFormulaFormula_GetGlobalProperty()
{
	static TWeakFieldPtr<FProperty> GlobalProperty = UAllTypesTestParamsFormulaFormula::StaticClass()->FindPropertyByName(GET_MEMBER_NAME_CHECKED(UAllTypesTestParamsFormulaFormula, Global));

	if (!GlobalProperty.IsValid())
	{
		UE_LOG(LogUAllTypesTestParamsFormulaFormula, Error, TEXT("Failed to find required 'Global' property on 'UAllTypesTestParamsFormulaFormula' type."));
	}
	return GlobalProperty.Get();
}

static FProperty* UAllTypesTestParamsFormulaFormula_GetInvokeParameterAt(int32 Index)
{
	static TArray<FProperty*> Parameters = []()
	{
		TArray<FProperty*> Params;
		for (TFieldIterator<FProperty> It(UAllTypesTestParamsFormulaFormula_GetInvokeFunction()); It; ++It)
		{
			FProperty* Prop = *It;

			if (Prop->HasAnyPropertyFlags(CPF_Parm) && !Prop->HasAnyPropertyFlags(CPF_ReturnParm))
			{
				Params.Add(Prop);
			}
		}
		return Params;
	}();

	check(Index >= 0 && Index < Parameters.Num());
	return Parameters[Index];
}

int32 UAllTypesTestParamsFormulaFormula::Invoke(int32 IntParam, FString StringParam, bool BoolParam, UObject* ObjectParam) const
{
	const int32 PARAMETER_INTPARAM_INDEX = 0;
	const int32 PARAMETER_STRINGPARAM_INDEX = 1;
	const int32 PARAMETER_BOOLPARAM_INDEX = 2;
	const int32 PARAMETER_OBJECTPARAM_INDEX = 3;

	auto __ParsedExpression = this->GetExpression();
	auto __InvokeFunction = UAllTypesTestParamsFormulaFormula_GetInvokeFunction();

	int32 __Result = {}; // default
	if (!__ParsedExpression.IsValid() || !__InvokeFunction)
	{
		UE_LOG(LogUAllTypesTestParamsFormulaFormula, Error, TEXT("The expression tree is missing or contains errors, or the function metadata is not available."));
		return __Result;
	}

	const TMap<FString, const TSharedRef<FFormulaValue>> __Arguments = {
		{ TEXT("intParam"), MakeShared<FFormulaValue>(UAllTypesTestParamsFormulaFormula_GetInvokeParameterAt(PARAMETER_INTPARAM_INDEX), &IntParam ) },
		{ TEXT("stringParam"), MakeShared<FFormulaValue>(UAllTypesTestParamsFormulaFormula_GetInvokeParameterAt(PARAMETER_STRINGPARAM_INDEX), &StringParam ) },
		{ TEXT("boolParam"), MakeShared<FFormulaValue>(UAllTypesTestParamsFormulaFormula_GetInvokeParameterAt(PARAMETER_BOOLPARAM_INDEX), &BoolParam ) },
		{ TEXT("objectParam"), MakeShared<FFormulaValue>(UAllTypesTestParamsFormulaFormula_GetInvokeParameterAt(PARAMETER_OBJECTPARAM_INDEX), &ObjectParam ) },
	};

	auto __Global = MakeShared<FFormulaValue>(UAllTypesTestParamsFormulaFormula_GetGlobalProperty(), &this->Global);
	auto __Context = FFormulaExecutionContext(this->AutoNullPropagation, __Arguments, __Global, UAllTypesTestParamsFormulaFormula_GetOrCreateTypeResolver());

	auto __ReturnValueType = __InvokeFunction->GetReturnProperty();
	auto __InvokeResult = __ParsedExpression->Execute(__Context, __ReturnValueType);
	if (__InvokeResult.HasError())
	{
		UE_LOG(LogUAllTypesTestParamsFormulaFormula, Error, TEXT("The formula [%s] execution failed. In this case, the default 'int32' result will be returned. Error: %s"), *__ParsedExpression->ToString(), *__InvokeResult.GetError().Message);
	}
	else if (!__InvokeResult.GetValue()->TryCopyCompleteValue(__ReturnValueType, &__Result))
	{
		UE_LOG(LogUAllTypesTestParamsFormulaFormula, Error, TEXT("Failed to convert Formula execution result '%s' to 'int32' type."), *__InvokeResult.GetValue()->ToString());
	}
	return __Result;
}

TSharedPtr<FFormulaExpression> UAllTypesTestParamsFormulaFormula::GetExpression() const
{
	if (!this->Expression.IsValid() && this->ExpressionTree.JsonObject.IsValid())
	{
		this->Expression = FExpressionBuildHelper::CreateExpression(&this->ExpressionTree.JsonObject);
	}
	return this->Expression;
}
#else
int32 UAllTypesTestParamsFormulaFormula::Invoke(int32 IntParam, FString StringParam, bool BoolParam, UObject* ObjectParam) const
{
	UE_LOG(LogUAllTypesTestParamsFormulaFormula, Error, TEXT("Formulas are not supported or disabled in this version of the plugin. Please update the Unreal Engine plugin to the latest version or enable the feature by adding the 'CHARON_FEATURE_FORMULAS_V2=1' compilation constant."));
	return {}; // default
}
#endif
