
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UAllTypesTestVoidFormulaFormula.h"
#include "UTestData.h"

DEFINE_LOG_CATEGORY(LogUAllTypesTestVoidFormulaFormula);

#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2

static TSharedRef<FFormulaTypeResolver> UAllTypesTestVoidFormulaFormula_GetOrCreateTypeResolver()
{
	static TSharedRef<FFormulaTypeResolver> __TypeResolver = MakeShared<FFormulaTypeResolver>(UTestData::GetSharedFormulaTypeResolver(), TArray<UObject*> {
	});

	return __TypeResolver;
}

static UFunction* UAllTypesTestVoidFormulaFormula_GetInvokeFunction()
{
	static TWeakObjectPtr<UFunction> InvokeFunction = UAllTypesTestVoidFormulaFormula::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UAllTypesTestVoidFormulaFormula, Invoke));

	if (!InvokeFunction.IsValid())
	{
		UE_LOG(LogUAllTypesTestVoidFormulaFormula, Error, TEXT("Failed to find required 'Invoke' function on 'UAllTypesTestVoidFormulaFormula' type."));
	}
	return InvokeFunction.Get();
}

static FProperty* UAllTypesTestVoidFormulaFormula_GetGlobalProperty()
{
	static TWeakFieldPtr<FProperty> GlobalProperty = UAllTypesTestVoidFormulaFormula::StaticClass()->FindPropertyByName(GET_MEMBER_NAME_CHECKED(UAllTypesTestVoidFormulaFormula, Global));

	if (!GlobalProperty.IsValid())
	{
		UE_LOG(LogUAllTypesTestVoidFormulaFormula, Error, TEXT("Failed to find required 'Global' property on 'UAllTypesTestVoidFormulaFormula' type."));
	}
	return GlobalProperty.Get();
}

static FProperty* UAllTypesTestVoidFormulaFormula_GetInvokeParameterAt(int32 Index)
{
	static TArray<FProperty*> Parameters = []()
	{
		TArray<FProperty*> Params;
		for (TFieldIterator<FProperty> It(UAllTypesTestVoidFormulaFormula_GetInvokeFunction()); It; ++It)
		{
			FProperty* Prop = *It;

			if (Prop->HasAnyPropertyFlags(CPF_Parm) && !Prop->HasAnyPropertyFlags(CPF_ReturnParm))
			{
				Params.Add(Prop);
			}
		}
		return Params;
	}();

	check(Index >= 0 && Index < Parameters.Num());
	return Parameters[Index];
}

void UAllTypesTestVoidFormulaFormula::Invoke() const
{

	auto __ParsedExpression = this->GetExpression();
	auto __InvokeFunction = UAllTypesTestVoidFormulaFormula_GetInvokeFunction();

	if (!__ParsedExpression.IsValid() || !__InvokeFunction)
	{
		UE_LOG(LogUAllTypesTestVoidFormulaFormula, Error, TEXT("The expression tree is missing or contains errors, or the function metadata is not available."));
		return;
	}

	const TMap<FString, const TSharedRef<FFormulaValue>> __Arguments = {
	};

	auto __Global = MakeShared<FFormulaValue>(UAllTypesTestVoidFormulaFormula_GetGlobalProperty(), &this->Global);
	auto __Context = FFormulaExecutionContext(this->AutoNullPropagation, __Arguments, __Global, UAllTypesTestVoidFormulaFormula_GetOrCreateTypeResolver());

	auto __ReturnValueType = __InvokeFunction->GetReturnProperty();
	auto __InvokeResult = __ParsedExpression->Execute(__Context, __ReturnValueType);
	if (__InvokeResult.HasError())
	{
		UE_LOG(LogUAllTypesTestVoidFormulaFormula, Error, TEXT("The formula [%s] execution failed. In this case, the default 'void' result will be returned. Error: %s"), *__ParsedExpression->ToString(), *__InvokeResult.GetError().Message);
	}
}

TSharedPtr<FFormulaExpression> UAllTypesTestVoidFormulaFormula::GetExpression() const
{
	if (!this->Expression.IsValid() && this->ExpressionTree.JsonObject.IsValid())
	{
		this->Expression = FExpressionBuildHelper::CreateExpression(&this->ExpressionTree.JsonObject);
	}
	return this->Expression;
}
#else
void UAllTypesTestVoidFormulaFormula::Invoke() const
{
	UE_LOG(LogUAllTypesTestVoidFormulaFormula, Error, TEXT("Formulas are not supported or disabled in this version of the plugin. Please update the Unreal Engine plugin to the latest version or enable the feature by adding the 'CHARON_FEATURE_FORMULAS_V2=1' compilation constant."));
	return {}; // default
}
#endif
