
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UNumberTestEntity.h"

const FString UNumberTestEntity::SchemaId = TEXT("592fdb43983a3619c016b696");
const FString UNumberTestEntity::SchemaName = TEXT("NumberTestEntity");

