
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "URecursiveEntity.h"

const FString URecursiveEntity::SchemaId = TEXT("592fc894983a36266c0912a4");
const FString URecursiveEntity::SchemaName = TEXT("RecursiveEntity");

