
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UTestEntityIntFormulaFormula.h"
#include "UTestData.h"

DEFINE_LOG_CATEGORY(LogUTestEntityIntFormulaFormula);

#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2

static TSharedRef<FFormulaTypeResolver> UTestEntityIntFormulaFormula_GetOrCreateTypeResolver()
{
	static TSharedRef<FFormulaTypeResolver> __TypeResolver = MakeShared<FFormulaTypeResolver>(UTestData::GetSharedFormulaTypeResolver(), TArray<UObject*> {
	});

	return __TypeResolver;
}

static UFunction* UTestEntityIntFormulaFormula_GetInvokeFunction()
{
	static TWeakObjectPtr<UFunction> InvokeFunction = UTestEntityIntFormulaFormula::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UTestEntityIntFormulaFormula, Invoke));

	if (!InvokeFunction.IsValid())
	{
		UE_LOG(LogUTestEntityIntFormulaFormula, Error, TEXT("Failed to find required 'Invoke' function on 'UTestEntityIntFormulaFormula' type."));
	}
	return InvokeFunction.Get();
}

static FProperty* UTestEntityIntFormulaFormula_GetGlobalProperty()
{
	static TWeakFieldPtr<FProperty> GlobalProperty = UTestEntityIntFormulaFormula::StaticClass()->FindPropertyByName(GET_MEMBER_NAME_CHECKED(UTestEntityIntFormulaFormula, Global));

	if (!GlobalProperty.IsValid())
	{
		UE_LOG(LogUTestEntityIntFormulaFormula, Error, TEXT("Failed to find required 'Global' property on 'UTestEntityIntFormulaFormula' type."));
	}
	return GlobalProperty.Get();
}

static FProperty* UTestEntityIntFormulaFormula_GetInvokeParameterAt(int32 Index)
{
	static TArray<FProperty*> Parameters = []()
	{
		TArray<FProperty*> Params;
		for (TFieldIterator<FProperty> It(UTestEntityIntFormulaFormula_GetInvokeFunction()); It; ++It)
		{
			FProperty* Prop = *It;

			if (Prop->HasAnyPropertyFlags(CPF_Parm) && !Prop->HasAnyPropertyFlags(CPF_ReturnParm))
			{
				Params.Add(Prop);
			}
		}
		return Params;
	}();

	check(Index >= 0 && Index < Parameters.Num());
	return Parameters[Index];
}

int32 UTestEntityIntFormulaFormula::Invoke(int32 First, int32 Second) const
{
	const int32 PARAMETER_FIRST_INDEX = 0;
	const int32 PARAMETER_SECOND_INDEX = 1;

	auto __ParsedExpression = this->GetExpression();
	auto __InvokeFunction = UTestEntityIntFormulaFormula_GetInvokeFunction();

	int32 __Result = {}; // default
	if (!__ParsedExpression.IsValid() || !__InvokeFunction)
	{
		UE_LOG(LogUTestEntityIntFormulaFormula, Error, TEXT("The expression tree is missing or contains errors, or the function metadata is not available."));
		return __Result;
	}

	const TMap<FString, const TSharedRef<FFormulaValue>> __Arguments = {
		{ TEXT("First"), MakeShared<FFormulaValue>(UTestEntityIntFormulaFormula_GetInvokeParameterAt(PARAMETER_FIRST_INDEX), &First ) },
		{ TEXT("Second"), MakeShared<FFormulaValue>(UTestEntityIntFormulaFormula_GetInvokeParameterAt(PARAMETER_SECOND_INDEX), &Second ) },
	};

	auto __Global = MakeShared<FFormulaValue>(UTestEntityIntFormulaFormula_GetGlobalProperty(), &this->Global);
	auto __Context = FFormulaExecutionContext(this->AutoNullPropagation, __Arguments, __Global, UTestEntityIntFormulaFormula_GetOrCreateTypeResolver());

	auto __ReturnValueType = __InvokeFunction->GetReturnProperty();
	auto __InvokeResult = __ParsedExpression->Execute(__Context, __ReturnValueType);
	if (__InvokeResult.HasError())
	{
		UE_LOG(LogUTestEntityIntFormulaFormula, Error, TEXT("The formula [%s] execution failed. In this case, the default 'int32' result will be returned. Error: %s"), *__ParsedExpression->ToString(), *__InvokeResult.GetError().Message);
	}
	else if (!__InvokeResult.GetValue()->TryCopyCompleteValue(__ReturnValueType, &__Result))
	{
		UE_LOG(LogUTestEntityIntFormulaFormula, Error, TEXT("Failed to convert Formula execution result '%s' to 'int32' type."), *__InvokeResult.GetValue()->ToString());
	}
	return __Result;
}

TSharedPtr<FFormulaExpression> UTestEntityIntFormulaFormula::GetExpression() const
{
	if (!this->Expression.IsValid() && this->ExpressionTree.JsonObject.IsValid())
	{
		this->Expression = FExpressionBuildHelper::CreateExpression(&this->ExpressionTree.JsonObject);
	}
	return this->Expression;
}
#else
int32 UTestEntityIntFormulaFormula::Invoke(int32 First, int32 Second) const
{
	UE_LOG(LogUTestEntityIntFormulaFormula, Error, TEXT("Formulas are not supported or disabled in this version of the plugin. Please update the Unreal Engine plugin to the latest version or enable the feature by adding the 'CHARON_FEATURE_FORMULAS_V2=1' compilation constant."));
	return {}; // default
}
#endif
