
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UTestDataProjectSettings.h"

const FString UTestDataProjectSettings::SchemaId = TEXT("55a4f32faca22e191098f3d9");
const FString UTestDataProjectSettings::SchemaName = TEXT("ProjectSettings");

