
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UTestEntityFormulaFieldFormula.h"
#include "UTestData.h"

DEFINE_LOG_CATEGORY(LogUTestEntityFormulaFieldFormula);

#if defined(CHARON_FEATURE_FORMULAS) && CHARON_FEATURE_FORMULAS
static TSharedPtr<FFormulaTypeResolver> __TypeResolver;

TSharedRef<FFormulaTypeResolver> GetOrCreateTypeResolver()
{
	if (__TypeResolver.IsValid())
	{
		return  __TypeResolver.ToSharedRef();
	}

	__TypeResolver = MakeShared<FFormulaTypeResolver>(UTestData::GetSharedFormulaTypeResolver(), TArray<UObject*> {
		AActor::StaticClass(),
	});

	return __TypeResolver.ToSharedRef();
}

TSharedPtr<TArray<TFieldPath<FProperty>>> UTestEntityFormulaFieldFormula::GetOrCreateInvokeParameters()
{
	if (!InvokeParameters.IsValid())
	{
		UClass* __FormulaClass = UTestEntityFormulaFieldFormula::StaticClass();
		UFunction* InvokeFunction = __FormulaClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UTestEntityFormulaFieldFormula, Invoke));
		InvokeParameters = MakeShared<TArray<TFieldPath<FProperty>>>();
		for (TFieldIterator<FProperty> It(InvokeFunction); It; ++It)
		{
			FProperty* Argument = *It;
			InvokeParameters->Add(Argument);
		}
		InvokeParameters->Add(__FormulaClass->FindPropertyByName(GET_MEMBER_NAME_CHECKED(UTestEntityFormulaFieldFormula, Global)));
	}
	return InvokeParameters;
}
FProperty* UTestEntityFormulaFieldFormula::GetInvokeParameterAt(int32 Index)
{
	auto Parameters = GetOrCreateInvokeParameters();
	Parameters->RangeCheck(Index);
	auto ParameterFieldPath = Parameters->GetData()[Index];

	check(ParameterFieldPath.Get() != nullptr);

	return ParameterFieldPath.Get();
}

int32 UTestEntityFormulaFieldFormula::Invoke(int32 Arg1, int32 Arg2, int32 Arg3, int32 Arg4)
{
	const int32 PARAMETER_ARG1_INDEX = 0;
	const int32 PARAMETER_ARG2_INDEX = 1;
	const int32 PARAMETER_ARG3_INDEX = 2;
	const int32 PARAMETER_ARG4_INDEX = 3;
	const int32 RETURN_PARAMETER_INDEX = 4;
	const int32 GLOBAL_PARAMETER_INDEX = 5;

	TSharedPtr<FFormulaExpression> ParsedExpression = this->GetExpression();
	int32 __Result = {};
	if (!ParsedExpression.IsValid())
	{
		UE_LOG(LogUTestEntityFormulaFieldFormula, Error, TEXT("ExpressionTree is missing or invalid."));
		return __Result; // default
	}

	const TMap<FString, FFormulaVariableValue> __Arguments = {
		{ TEXT("arg1"), FFormulaVariableValue(GetInvokeParameterAt(PARAMETER_ARG1_INDEX), &Arg1 ) },
		{ TEXT("arg2"), FFormulaVariableValue(GetInvokeParameterAt(PARAMETER_ARG2_INDEX), &Arg2 ) },
		{ TEXT("arg3"), FFormulaVariableValue(GetInvokeParameterAt(PARAMETER_ARG3_INDEX), &Arg3 ) },
		{ TEXT("arg4"), FFormulaVariableValue(GetInvokeParameterAt(PARAMETER_ARG4_INDEX), &Arg4 ) },
	};

	const FFormulaVariableValue __Global = FFormulaVariableValue(GetInvokeParameterAt(GLOBAL_PARAMETER_INDEX), &this->Global);
	const FFormulaExecutionContext __Context = FFormulaExecutionContext(this->AutoNullPropagation, __Arguments, __Global, GetOrCreateTypeResolver());

	const FFormulaVariableValue __VariableResult = ParsedExpression->Invoke(__Context);
	if (!__VariableResult.TryCopyCompleteValue(GetInvokeParameterAt(RETURN_PARAMETER_INDEX), &__Result))
	{
		UE_LOG(LogUTestEntityFormulaFieldFormula, Error, TEXT("Failed to convert Formula execution result %s to 'int32' type."), *__VariableResult.ToString());
	}
	return __Result;
}

TSharedPtr<FFormulaExpression> UTestEntityFormulaFieldFormula::GetExpression()
{
	if (!this->Expression.IsValid() && this->ExpressionTree.JsonObject.IsValid())
	{
		this->Expression = FExpressionBuildHelper::CreateExpression(&this->ExpressionTree.JsonObject);
	}
	return this->Expression;
}
#else
int32 UTestEntityFormulaFieldFormula::Invoke(int32 Arg1, int32 Arg2, int32 Arg3, int32 Arg4)
{
	UE_LOG(LogUTestEntityFormulaFieldFormula, Error, TEXT("Formulas are not supported or disabled in this version of the plugin. Please update the Unreal Engine plugin to the latest version or enable the feature by adding the 'CHARON_FEATURE_FORMULAS=1' compilation constant."));
	return {}; // default
}
#endif
