
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UTestEntityFormulaFieldFormula.h"
#include "UTestData.h"

DEFINE_LOG_CATEGORY(LogUTestEntityFormulaFieldFormula);

#if defined(CHARON_FEATURE_FORMULAS_V2) && CHARON_FEATURE_FORMULAS_V2

static TSharedRef<FFormulaTypeResolver> GetOrCreateTypeResolver()
{
	static TSharedRef<FFormulaTypeResolver> __TypeResolver = MakeShared<FFormulaTypeResolver>(UTestData::GetSharedFormulaTypeResolver(), TArray<UObject*> {
		AActor::StaticClass(),
	});

	return __TypeResolver;
}

static UFunction* GetInvokeFunction()
{
	static TWeakObjectPtr<UFunction> InvokeFunction = UTestEntityFormulaFieldFormula::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UTestEntityFormulaFieldFormula, Invoke));

	if (!InvokeFunction.IsValid())
	{
		UE_LOG(LogUTestEntityFormulaFieldFormula, Error, TEXT("Failed to find required 'Invoke' function on 'UTestEntityFormulaFieldFormula' type."));
	}
	return InvokeFunction.Get();
}

static FProperty* GetGlobalProperty()
{
	static TWeakFieldPtr<FProperty> GlobalProperty = UTestEntityFormulaFieldFormula::StaticClass()->FindPropertyByName(GET_MEMBER_NAME_CHECKED(UTestEntityFormulaFieldFormula, Global));

	if (!GlobalProperty.IsValid())
	{
		UE_LOG(LogUTestEntityFormulaFieldFormula, Error, TEXT("Failed to find required 'Global' property on 'UTestEntityFormulaFieldFormula' type."));
	}
	return GlobalProperty.Get();
}

static FProperty* GetInvokeParameterAt(int32 Index)
{
	static TArray<FProperty*> Parameters = []()
	{
		TArray<FProperty*> Params;
		for (TFieldIterator<FProperty> It(GetInvokeFunction()); It; ++It)
		{
			FProperty* Prop = *It;

			if (Prop->HasAnyPropertyFlags(CPF_Parm) && !Prop->HasAnyPropertyFlags(CPF_ReturnParm))
			{
				Params.Add(Prop);
			}
		}
		return Params;
	}();

	check(Index >= 0 && Index < Parameters.Num());
	return Parameters[Index];
}

int32 UTestEntityFormulaFieldFormula::Invoke(int32 Arg1, int32 Arg2, int32 Arg3, int32 Arg4) const
{
	const int32 PARAMETER_ARG1_INDEX = 0;
	const int32 PARAMETER_ARG2_INDEX = 1;
	const int32 PARAMETER_ARG3_INDEX = 2;
	const int32 PARAMETER_ARG4_INDEX = 3;

	auto __ParsedExpression = this->GetExpression();
	auto __InvokeFunction = GetInvokeFunction();

	int32 __Result = {};
	if (!__ParsedExpression.IsValid() || !__InvokeFunction)
	{
		UE_LOG(LogUTestEntityFormulaFieldFormula, Error, TEXT("The expression tree is missing or contains errors, or the function metadata is not available."));
		return __Result; // default
	}

	const TMap<FString, const TSharedRef<FFormulaValue>> __Arguments = {
		{ TEXT("arg1"), MakeShared<FFormulaValue>(GetInvokeParameterAt(PARAMETER_ARG1_INDEX), &Arg1 ) },
		{ TEXT("arg2"), MakeShared<FFormulaValue>(GetInvokeParameterAt(PARAMETER_ARG2_INDEX), &Arg2 ) },
		{ TEXT("arg3"), MakeShared<FFormulaValue>(GetInvokeParameterAt(PARAMETER_ARG3_INDEX), &Arg3 ) },
		{ TEXT("arg4"), MakeShared<FFormulaValue>(GetInvokeParameterAt(PARAMETER_ARG4_INDEX), &Arg4 ) },
	};

	auto __Global = MakeShared<FFormulaValue>(GetGlobalProperty(), &this->Global);
	auto __Context = FFormulaExecutionContext(this->AutoNullPropagation, __Arguments, __Global, GetOrCreateTypeResolver());

	auto __ReturnValueType = __InvokeFunction->GetReturnProperty();
	auto __InvokeResult = __ParsedExpression->Execute(__Context, __ReturnValueType);
	if (__InvokeResult.HasError())
	{
		UE_LOG(LogUTestEntityFormulaFieldFormula, Error, TEXT("The formula [%s] execution failed. In this case, the default 'int32' result will be returned. Error: %s"), *__ParsedExpression->ToString(), *__InvokeResult.GetError().Message);
	}
	else if (!__InvokeResult.GetValue()->TryCopyCompleteValue(__ReturnValueType, &__Result))
	{
		UE_LOG(LogUTestEntityFormulaFieldFormula, Error, TEXT("Failed to convert Formula execution result '%s' to 'int32' type."), *__InvokeResult.GetValue()->ToString());
	}
	return __Result;
}

TSharedPtr<FFormulaExpression> UTestEntityFormulaFieldFormula::GetExpression() const
{
	if (!this->Expression.IsValid() && this->ExpressionTree.JsonObject.IsValid())
	{
		this->Expression = FExpressionBuildHelper::CreateExpression(&this->ExpressionTree.JsonObject);
	}
	return this->Expression;
}
#else
int32 UTestEntityFormulaFieldFormula::Invoke(int32 Arg1, int32 Arg2, int32 Arg3, int32 Arg4) const
{
	UE_LOG(LogUTestEntityFormulaFieldFormula, Error, TEXT("Formulas are not supported or disabled in this version of the plugin. Please update the Unreal Engine plugin to the latest version or enable the feature by adding the 'CHARON_FEATURE_FORMULAS_V2=1' compilation constant."));
	return {}; // default
}
#endif
