
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UTestEntity.h"
#include "UTestEntityFormulaFieldFormula.h"
#include "UUnionType.h"

const FString UTestEntity::SchemaId = TEXT("592fc86c983a36266c0912a0");
const FString UTestEntity::SchemaName = TEXT("TestEntity");

FText UTestEntity::GetLocalizedTextField() {
	return LocalizedTextFieldRaw.GetCurrent();
}
UTestEntity* UTestEntity::GetReferenceField() {
		FGameDataDocumentReference::GetReferencedDocument(ReferenceFieldRaw, _referenceFieldDocument);
		return _referenceFieldDocument;
}
TMap<FString,UTestEntity*> UTestEntity::GetListOfReferencesField() {
	FGameDataDocumentReference::GetReferencedDocuments(ListOfReferencesFieldRaw, _listOfReferencesFieldDocuments);
	return _listOfReferencesFieldDocuments;
}
