
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UUnionType.h"
#include "UNumberTestEntity.h"

const FString UUnionType::SchemaId = TEXT("691255870642d17fc832c712");
const FString UUnionType::SchemaName = TEXT("UnionType");

FText UUnionType::GetTextLocalizable2() {
	return TextLocalizable2Raw.GetCurrent();
}
UNumberTestEntity* UUnionType::GetReference12() {
		FGameDataDocumentReference::GetReferencedDocument(Reference12Raw, _reference12Document);
		return _reference12Document;
}
TMap<int32,UNumberTestEntity*> UUnionType::GetCollectionofReferences13() {
	FGameDataDocumentReference::GetReferencedDocuments(CollectionofReferences13Raw, _collectionofReferences13Documents);
	return _collectionofReferences13Documents;
}
void UUnionType::Apply(FUnionVisitor& visitor)
{
	if (this->Tag == TEXT("Text1"))
	{
		return visitor.VisitText1(this->Text1);
	}
	if (this->Tag == TEXT("TextLocalizable2"))
	{
		return visitor.VisitTextLocalizable2(this->GetTextLocalizable2());
	}
	if (this->Tag == TEXT("Logical3"))
	{
		return visitor.VisitLogical3(this->Logical3);
	}
	if (this->Tag == TEXT("Time4"))
	{
		return visitor.VisitTime4(this->Time4);
	}
	if (this->Tag == TEXT("Date5"))
	{
		return visitor.VisitDate5(this->Date5);
	}
	if (this->Tag == TEXT("Number6"))
	{
		return visitor.VisitNumber6(this->Number6);
	}
	if (this->Tag == TEXT("NumberInteger7"))
	{
		return visitor.VisitNumberInteger7(this->NumberInteger7);
	}
	if (this->Tag == TEXT("PickList8"))
	{
		return visitor.VisitPickList8(this->PickList8);
	}
	if (this->Tag == TEXT("MultiPickList9"))
	{
		return visitor.VisitMultiPickList9(this->MultiPickList9);
	}
	if (this->Tag == TEXT("Document10"))
	{
		return visitor.VisitDocument10(this->Document10);
	}
	if (this->Tag == TEXT("CollectionofDocuments11"))
	{
		return visitor.VisitCollectionofDocuments11(this->CollectionofDocuments11);
	}
	if (this->Tag == TEXT("Reference12"))
	{
		return visitor.VisitReference12(this->GetReference12());
	}
	if (this->Tag == TEXT("CollectionofReferences13"))
	{
		return visitor.VisitCollectionofReferences13(this->GetCollectionofReferences13());
	}
	if (this->Tag == TEXT("Formula14"))
	{
		return visitor.VisitFormula14(this->Formula14);
	}
	else {
		return visitor.UnknownTag(this->Tag);
	}
}
