
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UUniqueAttributeEntity.h"

const FString UUniqueAttributeEntity::SchemaId = TEXT("65d3565e27363a98010000ec");
const FString UUniqueAttributeEntity::SchemaName = TEXT("UniqueAttributeEntity");

