
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: CrossbowerArmor1 - 0, Used in Schemas: Armor.
  */
struct RPGGAMEDATA_API EArmorId {
public:
	static const FString CrossbowerArmor1;
	static const FString CrossbowerArmor2;
	static const FString CrossbowerArmor3;
	static const FString CrossbowerArmor4;
	static const FString CrossbowerArmor5;
	static const FString MonstrosityArmor1;
	static const FString MonstrosityArmor2;
	static const FString MonstrosityArmor3;
	static const FString MonstrosityArmor4;
	static const FString MonstrosityArmor5;
	static const FString ZealotArmor1;
	static const FString ZealotArmor2;
	static const FString ZealotArmor3;
	static const FString ZealotArmor4;
	static const FString ZealotArmor5;
};
