
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: AboveDimLight - 0, Used in Schemas: Conditions.
  */
struct RPGGAMEDATA_API EConditionsId {
public:
	static const FString AboveDimLight;
	static const FString Dark;
	static const FString FirstRound;
	static const FString LocationHarbor;
	static const FString LocationLabyrinth;
	static const FString LocationRuins;
	static const FString LocationWoodland;
	static const FString LowHealth;
	static const FString MeleeAttack;
	static const FString MonsterTypeBeast;
	static const FString MonsterTypeCorpse;
	static const FString MonsterTypeEldritch;
	static const FString MonsterTypeHuman;
	static const FString MonsterTypeUnholy;
	static const FString RadiantLight;
	static const FString RangedAttack;
	static const FString Shadowy;
	static const FString Stressed;
};
