
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "Misc/TVariant.h"

/**
  * Enumeration based on int32. Default Value: Corridor - 0, Flags, Used in Schemas: Curio.
  */
UENUM(BlueprintType, meta = (Bitflags, UseEnumValuesAsMaskValuesInEditor = "true"))
enum class ECurioPlacementRestictions : uint8 {
		None = 0  UMETA(DisplayName = "None"),
		Room = 1  UMETA(DisplayName = "Room"),
		Corridor = 2  UMETA(DisplayName = "Corridor"),
};
ENUM_CLASS_FLAGS(ECurioPlacementRestictions);

/** Implements variant type traits for enumeration type. */
template<> struct TVariantTraits<ECurioPlacementRestictions>
{
	static constexpr EVariantTypes GetType() { return EVariantTypes::Enum; }
};
