
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: Crate - 0, Used in Schemas: Curio.
  */
struct RPGGAMEDATA_API ECurioId {
public:
	static const FString Crate;
	static const FString EldritchAltar;
	static const FString LockedSarcophagus;
	static const FString MeatCart;
	static const FString Sconce;
};
