
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: BadHumors - 0, Used in Schemas: Disease.
  */
struct RPGGAMEDATA_API EDiseaseId {
public:
	static const FString BadHumors;
	static const FString CreepingCough;
	static const FString Ennui;
	static const FString Hemophilia;
	static const FString Rabies;
	static const FString TheRuns;
};
