
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "Misc/TVariant.h"

/**
  * Enumeration based on int32. Used in Schemas: CombatEffect.
  */
UENUM(BlueprintType)
enum class EDurationUnit : uint8 {
	None = 0  UMETA(DisplayName = "None"),
	Rounds = 1  UMETA(DisplayName = "Rounds"),
	Camps = 2  UMETA(DisplayName = "Camps"),
	Missions = 3  UMETA(DisplayName = "Missions"),
};

/** Implements variant type traits for enumeration type. */
template<> struct TVariantTraits<EDurationUnit>
{
	static constexpr EVariantTypes GetType() { return EVariantTypes::Enum; }
};
