
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: AccuracyStone - 0, Used in Schemas: Item.
  */
struct RPGGAMEDATA_API EItemId {
public:
	static const FString AccuracyStone;
	static const FString AncestorsRelic;
	static const FString Antivenom;
	static const FString Bandage;
	static const FString BeastSlayersRing;
	static const FString Bust;
	static const FString CautionCloak;
	static const FString Citrine;
	static const FString Crest;
	static const FString DarkBracer;
	static const FString Deed;
	static const FString DogTreats;
	static const FString Emerald;
	static const FString Firewood;
	static const FString Food;
	static const FString Gold;
	static const FString GrainSack;
	static const FString HandofGlory;
	static const FString HerbalRemedies;
	static const FString HerosRing;
	static const FString HolyRelic;
	static const FString HolyWater;
	static const FString Jade;
	static const FString JuteTapestry;
	static const FString Medicine;
	static const FString MinorAntique;
	static const FString Onyx;
	static const FString PickAxe;
	static const FString PinealGland;
	static const FString Portrait;
	static const FString PotentSalve;
	static const FString ProtectivePadlock;
	static const FString PuzzlingTrapezohedron;
	static const FString RareAntique;
	static const FString Ruby;
	static const FString Sapphire;
	static const FString Shovel;
	static const FString SkeletonKey;
	static const FString Torch;
};
