
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "Misc/TVariant.h"

/**
  * Enumeration based on int32. Default Value: Tutorial - 0, Flags, Used in Schemas: Location.
  */
UENUM(BlueprintType, meta = (Bitflags, UseEnumValuesAsMaskValuesInEditor = "true"))
enum class ELocationFlags : uint8 {
		None = 0  UMETA(DisplayName = "None"),
		Home = 1  UMETA(DisplayName = "Home"),
		Tutorial = 2  UMETA(DisplayName = "Tutorial"),
};
ENUM_CLASS_FLAGS(ELocationFlags);

/** Implements variant type traits for enumeration type. */
template<> struct TVariantTraits<ELocationFlags>
{
	static constexpr EVariantTypes GetType() { return EVariantTypes::Enum; }
};
