
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: Harbor - 0, Used in Schemas: Location.
  */
struct RPGGAMEDATA_API ELocationId {
public:
	static const FString Harbor;
	static const FString Labyrinth;
	static const FString Ruins;
	static const FString TheDarkCavern;
	static const FString TheOldRoad;
	static const FString TheVillage;
	static const FString Woodland;
};
