
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "Misc/TVariant.h"

/**
  * Enumeration based on int32. Used in Schemas: Loot.
  */
UENUM(BlueprintType)
enum class ELootType : uint8 {
	None = 0  UMETA(DisplayName = "None"),
	Any = 1  UMETA(DisplayName = "Any"),
	Heirloom = 2  UMETA(DisplayName = "Heirloom"),
	Trinket = 3  UMETA(DisplayName = "Trinket"),
	Supplies = 4  UMETA(DisplayName = "Supplies"),
	Torch = 5  UMETA(DisplayName = "Torch"),
	Gold = 6  UMETA(DisplayName = "Gold"),
	Food = 7  UMETA(DisplayName = "Food"),
};

/** Implements variant type traits for enumeration type. */
template<> struct TVariantTraits<ELootType>
{
	static constexpr EVariantTypes GetType() { return EVariantTypes::Enum; }
};
