
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: BoneCourtier - 0, Used in Schemas: Monster.
  */
struct RPGGAMEDATA_API EMonsterId {
public:
	static const FString BoneCourtier;
	static const FString BoneSoldier;
	static const FString CultistAcolyte;
	static const FString CultistFighter;
	static const FString PorkChopper;
	static const FString PorkWretch;
};
