
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "Misc/TVariant.h"

/**
  * Enumeration based on int32. Used in Schemas: Parameter.
  */
UENUM(BlueprintType)
enum class EParameterId : uint8 {
	None = 0  UMETA(DisplayName = "None"),
	HitPoints = 1  UMETA(DisplayName = "HitPoints"),
	MaxHitPoints = 2  UMETA(DisplayName = "MaxHitPoints"),
	MaxHitPointsPercent = 3  UMETA(DisplayName = "MaxHitPointsPercent"),
	Speed = 4  UMETA(DisplayName = "Speed"),
	Accuracy = 5  UMETA(DisplayName = "Accuracy"),
	CrtiticalStrikeChance = 6  UMETA(DisplayName = "CrtiticalStrikeChance"),
	Stress = 7  UMETA(DisplayName = "Stress"),
	Dodge = 8  UMETA(DisplayName = "Dodge"),
	Protection = 9  UMETA(DisplayName = "Protection"),
	ScoutingChance = 10  UMETA(DisplayName = "ScoutingChance"),
	FoodConsumationMultiplier = 11  UMETA(DisplayName = "FoodConsumationMultiplier"),
	HealResistance = 20  UMETA(DisplayName = "HealResistance"),
	StunResistance = 21  UMETA(DisplayName = "StunResistance"),
	BlightResistance = 22  UMETA(DisplayName = "BlightResistance"),
	DiseaseResistance = 23  UMETA(DisplayName = "DiseaseResistance"),
	DeathBlowResistance = 24  UMETA(DisplayName = "DeathBlowResistance"),
	MoveResistance = 25  UMETA(DisplayName = "MoveResistance"),
	BleedResistance = 26  UMETA(DisplayName = "BleedResistance"),
	DebuffResistance = 27  UMETA(DisplayName = "DebuffResistance"),
	TrapResistance = 28  UMETA(DisplayName = "TrapResistance"),
	StressResistance = 29  UMETA(DisplayName = "StressResistance"),
	HealAmplification = 30  UMETA(DisplayName = "HealAmplification"),
	StressHealAplification = 31  UMETA(DisplayName = "StressHealAplification"),
	DamageFrom = 50  UMETA(DisplayName = "DamageFrom"),
	DamageTo = 51  UMETA(DisplayName = "DamageTo"),
	DamagePercent = 52  UMETA(DisplayName = "DamagePercent"),
	HealFrom = 53  UMETA(DisplayName = "HealFrom"),
	HealTo = 54  UMETA(DisplayName = "HealTo"),
	HealMultiplier = 55  UMETA(DisplayName = "HealMultiplier"),
	HealPercent = 56  UMETA(DisplayName = "HealPercent"),
	StressHealFrom = 57  UMETA(DisplayName = "StressHealFrom"),
	StressHealTo = 58  UMETA(DisplayName = "StressHealTo"),
	StressHealPercent = 59  UMETA(DisplayName = "StressHealPercent"),
	BleedHealChance = 60  UMETA(DisplayName = "BleedHealChance"),
	StunChance = 70  UMETA(DisplayName = "StunChance"),
	MarkChance = 71  UMETA(DisplayName = "MarkChance"),
	KnockbackChance = 73  UMETA(DisplayName = "KnockbackChance"),
	VirtueChance = 74  UMETA(DisplayName = "VirtueChance"),
	Position = 80  UMETA(DisplayName = "Position"),
};

/** Implements variant type traits for enumeration type. */
template<> struct TVariantTraits<EParameterId>
{
	static constexpr EVariantTypes GetType() { return EVariantTypes::Enum; }
};
