
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "Misc/TVariant.h"

/**
  * Enumeration based on int32. Used in Schemas: Parameter.
  */
UENUM(BlueprintType)
enum class EParameterValueKind : uint8 {
	None = 0  UMETA(DisplayName = "None"),
	Integer = 1  UMETA(DisplayName = "Integer"),
	Number = 2  UMETA(DisplayName = "Number"),
	Percent = 3  UMETA(DisplayName = "Percent"),
};

/** Implements variant type traits for enumeration type. */
template<> struct TVariantTraits<EParameterValueKind>
{
	static constexpr EVariantTypes GetType() { return EVariantTypes::Enum; }
};
