
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: Antivenom - 0, Used in Schemas: Provision.
  */
struct RPGGAMEDATA_API EProvisionId {
public:
	static const FString Antivenom;
	static const FString Bandage;
	static const FString DogTreats;
	static const FString Firewood;
	static const FString Food;
	static const FString HerbalRemedies;
	static const FString HolyWater;
	static const FString Shovel;
	static const FString SkeletonKey;
	static const FString Torch;
};
