
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: Anemic - 0, Used in Schemas: Quirk.
  */
struct RPGGAMEDATA_API EQuirkId {
public:
	static const FString Anemic;
	static const FString BeastHater;
	static const FString Clotter;
	static const FString Clumsy;
	static const FString Evasive;
	static const FString FearOfBeasts;
	static const FString HarborAdventurer;
	static const FString HarborPhobe;
};
