
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: AccuracyStone - 0, Used in Schemas: Trinket.
  */
struct RPGGAMEDATA_API ETrinketId {
public:
	static const FString AccuracyStone;
	static const FString BeastSlayersRing;
	static const FString CautionCloak;
	static const FString DarkBracer;
	static const FString HerosRing;
	static const FString ProtectivePadlock;
};
