
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Misc/DateTime.h"
#include "Misc/Timespan.h"
// ReSharper disable All

/**
  * Enumeration based on FString. Default Value: CrossbowerWeapon1 - 0, Used in Schemas: Weapon.
  */
struct RPGGAMEDATA_API EWeaponId {
public:
	static const FString CrossbowerWeapon1;
	static const FString CrossbowerWeapon2;
	static const FString CrossbowerWeapon3;
	static const FString CrossbowerWeapon4;
	static const FString CrossbowerWeapon5;
	static const FString MonstrosityWeapon1;
	static const FString MonstrosityWeapon2;
	static const FString MonstrosityWeapon3;
	static const FString MonstrosityWeapon4;
	static const FString MonstrosityWeapon5;
	static const FString ZealotWeapon1;
	static const FString ZealotWeapon2;
	static const FString ZealotWeapon3;
	static const FString ZealotWeapon4;
	static const FString ZealotWeapon5;
};
