
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "JsonObjectWrapper.h"

#include "EDurationUnit.h"
#include "UCombatEffect.generated.h"

class UParameterValue; // forward declaration

/**
  * Combat Effect with Integer id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UCombatEffect : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

public:
	/**
	  * Id property of Integer type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Id;
	/**
	  * Changes property of Document Collection type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<int32,UParameterValue*> Changes;
	/**
	  * zero or empty - effect is permanent. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Duration;
	/**
	  * Duration Unit property of Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	EDurationUnit DurationUnit;
};
