
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UObject/Class.h"
#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "JsonObjectWrapper.h"
#if defined(CHARON_FEATURE_FORMULAS) && CHARON_FEATURE_FORMULAS
#include "GameData/Formulas/FFormulaExpression.h"
#include "GameData/Formulas/FExpressionBuildHelper.h"
#include "GameData/Formulas/FFormulaTypeResolver.h"
#include "GameData/Formulas/FFormulaExecutionContext.h"
#include "GameData/Formulas/FFormulaVariableValue.h"
#endif
#if __has_include("URpgGameDataFormulaTypes.h")
    #include "URpgGameDataFormulaTypes.h"
#endif

DECLARE_LOG_CATEGORY_EXTERN(LogUConditionsCheckFormula, Log, All);

#include "UConditionsCheckFormula.generated.h"

/**
  * Formula Signature: (UObject context) -> System.Boolean
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UConditionsCheckFormula : public UObject
{
	GENERATED_BODY()

private:
#if defined(CHARON_FEATURE_FORMULAS) && CHARON_FEATURE_FORMULAS
	TSharedPtr<TArray<TFieldPath<FProperty>>> InvokeParameters;
	TSharedPtr<FFormulaExpression> Expression;
#endif
public:
	/**
	  * Gets or sets the Abstract Syntax Tree (AST) of the formula. Used internally.
	  */
	UPROPERTY()
	FJsonObjectWrapper ExpressionTree;
	/**
	  * Gets or sets the root provider for global identifiers. Properties and methods of this
	  * object can be referenced directly within the formula without a qualifier.
	  */
	UPROPERTY()
	TObjectPtr<UObject> Global;
	/**
	  * Gets or sets a value indicating whether null propagation should be applied
	  * implicitly to this formula during evaluation or code generation.
	  */
	UPROPERTY()
	bool AutoNullPropagation;

	/**
	  * Evaluates the formula and returns the resulting value.
	  */
	UFUNCTION()
	bool Invoke(UObject* Context);

#if defined(CHARON_FEATURE_FORMULAS) && CHARON_FEATURE_FORMULAS
	/**
	  * Gets original formula expression for custom interpretation.
	  */
	TSharedPtr<FFormulaExpression> GetExpression();
private:
	TSharedPtr<TArray<TFieldPath<FProperty>>> GetOrCreateInvokeParameters();
	FProperty* GetInvokeParameterAt(int32 Index);
#endif
};
