
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "UObject/Class.h"
#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "JsonObjectWrapper.h"

#include "UConditionsCheckFormula.generated.h"

/**
  * Formula Signature: (Assets.Scripts.CheckContext context) -> System.Boolean
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UConditionsCheckFormula : public UObject
{
	GENERATED_BODY()

public:
	UPROPERTY()
	FJsonObjectWrapper ExpressionTree;

	UConditionsCheckFormula() { }
};
