
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"

#include "UCurioCleansingOption.generated.h"

class UItem; // forward declaration
class ULoot; // forward declaration
class UParameterValue; // forward declaration

/**
  * Curio Cleansing Option with Integer id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UCurioCleansingOption : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

	/**
	  * De-referenced document of Item. Should not be directly used.
	  */
	UItem* _itemDocument;
public:
	/**
	  * Id property of Integer type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Id;
	/**
	  * Chance of happening of this cleansing option relative to other options. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float Chance;
	/**
	  * Cleansing item. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	UItem* GetItem();
	/**
	  * Raw value of Item.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference ItemRaw;
	/**
	  * Loot property of Document Collection type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<int32,ULoot*> Loot;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Positive value is for positive quirks and negative for negative quirks. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float QuirkChance;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float DiseaseChance;
	/**
	  * Effects property of Document Collection type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<int32,UParameterValue*> Effects;
	/**
	  * Item Is Consumed property of Logical type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	bool ItemIsConsumed;
};
