
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "JsonObjectWrapper.h"

#include "UHero.generated.h"

class UProvision; // forward declaration
class UArmor; // forward declaration
class UWeapon; // forward declaration

/**
  * Heroes with Text id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UHero : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

	/**
	  * De-referenced collection of documents for DislikeHeroes. Should not be directly used.
	  */
	TMap<FString,UHero*> _dislikeHeroesDocuments;
	/**
	  * De-referenced document of Provisions. Should not be directly used.
	  */
	UProvision* _provisionsDocument;
public:
	/**
	  * Id property of Text type. Not Empty, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Id;
	/**
	  * Name property of Localized Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FText GetName();
	/**
	  * Raw value of Name.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FLocalizedText NameRaw;
	/**
	  * Bio property of Localized Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FText GetBio();
	/**
	  * Raw value of Bio.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FLocalizedText BioRaw;
	/**
	  * Religious property of Logical type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	bool Religious;
	/**
	  * List of heroes which dislikes current hero. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	TMap<FString,UHero*> GetDislikeHeroes();
	/**
	  * Raw value of DislikeHeroes.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TArray<FGameDataDocumentReference> DislikeHeroesRaw;
	/**
	  * Provisions property of Reference type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	UProvision* GetProvisions();
	/**
	  * Raw value of Provisions.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference ProvisionsRaw;
	/**
	  * Provisions Count property of Integer type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 ProvisionsCount;
	/**
	  * Maximum possible change in the position of the hero. Direction - forward. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 MovementForward;
	/**
	  * Maximum possible change in the position of the hero. Direction - backward. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 MovementBackward;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Protection;
	/**
	  * Accuracy Modifier property of Integer type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 AccuracyModifier;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float StunResistance;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float BlightResistance;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float DiseaseResistance;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float DeathBlowResistance;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float MoveResistance;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float BleedResistance;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float DebuffResistance;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float TrapResistance;
	/**
	  * Armors property of Document Collection type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<FString,UArmor*> Armors;
	/**
	  * Weapons property of Document Collection type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<FString,UWeapon*> Weapons;
	/**
	  * Picture property of Text type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Picture;
};
