
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "JsonObjectWrapper.h"

#include "UItem.generated.h"

class UParameterValue; // forward declaration

/**
  * Item with Text id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UItem : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

public:
	/**
	  * Id property of Text type. Not Empty, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Id;
	/**
	  * Name property of Localized Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FText GetName();
	/**
	  * Raw value of Name.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FLocalizedText NameRaw;
	/**
	  * Description property of Localized Text type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	FText GetDescription();
	/**
	  * Raw value of Description.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FLocalizedText DescriptionRaw;
	/**
	  * Zero and one mean - non stackable. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 StackSize;
	/**
	  * Gold value of treasure. Rewared upon completion of mission. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 GoldValue;
	/**
	  * Activation Effects property of Document Collection type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<int32,UParameterValue*> ActivationEffects;
};
