
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"

#include "UItemWithCount.generated.h"

class UItem; // forward declaration

/**
  * Item With Count with Integer id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UItemWithCount : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

	/**
	  * De-referenced document of Item. Should not be directly used.
	  */
	UItem* _itemDocument;
public:
	/**
	  * Id property of Integer type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Id;
	/**
	  * Item property of Reference type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	UItem* GetItem();
	/**
	  * Raw value of Item.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference ItemRaw;
	/**
	  * Count property of Integer type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Count;
};
