
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"

#include "ELootType.h"
#include "ULoot.generated.h"


/**
  * Loot with Integer id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API ULoot : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

public:
	/**
	  * Id property of Integer type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Id;
	/**
	  * Type property of Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ELootType Type;
	/**
	  * Amount property of Integer type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Amount;
};
