
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "GameData/UGameDataLibrary.h"
#include "JsonObjectWrapper.h"
#include "Misc/EngineVersionComparison.h"

#include "UParameterValue.generated.h"

class UParameter; // forward declaration
class UCondition; // forward declaration

/**
  * Parameter Value with Integer id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UParameterValue : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

	/**
	  * De-referenced document of Parameter. Should not be directly used.
	  */
	UPROPERTY()
	mutable UParameter* _ParameterDocument;
	/**
	  * De-referenced document of Condition. Should not be directly used.
	  */
	UPROPERTY()
	mutable UCondition* _ConditionDocument;
public:
	/**
	  * Id property of Integer type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Id;
	/**
	  * Parameter property of Reference type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	UParameter* GetParameter() const;
	/**
	  * Raw value of Parameter.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference ParameterRaw;
	/**
	  * Value property of Number type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float Value;
	/**
	  * Condition property of Reference type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	UCondition* GetCondition() const;
	/**
	  * Raw value of Condition.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference ConditionRaw;
	/**
	  * Effect Tags property of Text type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString EffectTags;
	/**
	  * Effect Tags property of Text type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	TArray<FString> GetParsedEffectTags() const;
};
