
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "JsonObjectWrapper.h"

#include "EParameterId.h"
#include "EParameterValueKind.h"
#include "UParameter.generated.h"


/**
  * Parameter with PickList id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UParameter : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

	/**
	  * De-referenced document of MinValueParameter. Should not be directly used.
	  */
	UParameter* _minValueParameterDocument;
	/**
	  * De-referenced document of MaxValueParameter. Should not be directly used.
	  */
	UParameter* _maxValueParameterDocument;
public:
	/**
	  * Id property of Pick List type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	EParameterId Id;
	/**
	  * Maximal value for this attribute. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float MinValue;
	/**
	  * Maximal value for this attribute. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float MaxValue;
	/**
	  * Min Value Parameter property of Reference type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	UParameter* GetMinValueParameter();
	/**
	  * Raw value of MinValueParameter.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference MinValueParameterRaw;
	/**
	  * Max Value Parameter property of Reference type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	UParameter* GetMaxValueParameter();
	/**
	  * Raw value of MaxValueParameter.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference MaxValueParameterRaw;
	/**
	  * Value Kind property of Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	EParameterValueKind ValueKind;
};
