
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2026
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"
#include "JsonObjectWrapper.h"

#include "UProvision.generated.h"

class UItem; // forward declaration

/**
  * Provisions with Text id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UProvision : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

public:
	/**
	  * Id property of Text type. Not Empty, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Id;
	/**
	  * Cost of provision in gold. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Cost;
	/**
	  * Item property of Document type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	UItem* Item;
};
