
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"

#include "UQuirk.generated.h"

class UParameterValue; // forward declaration

/**
  * Quirks with Text id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UQuirk : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

public:
	/**
	  * Id property of Text type. Not Empty, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Id;
	/**
	  * Name property of Localized Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FText GetName();
	/**
	  * Raw value of Name.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FLocalizedText NameRaw;
	/**
	  * Is Positive property of Logical type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	bool IsPositive;
	/**
	  * Effects property of Document Collection type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<int32,UParameterValue*> Effects;
};
