
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"

#include "URpgGameDataProjectSettings.generated.h"


/**
  * Project Settings with Text id. Settings.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API URpgGameDataProjectSettings : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

public:
	/**
	  * Id property of Text type. Not Empty, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Id;
	/**
	  * Project Name property of Text type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Name;
	/**
	  * Primary Language property of Text type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString PrimaryLanguage;
	/**
	  * Languages property of Text type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Languages;
	/**
	  * Copyright property of Text type. Can Be Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Copyright;
	/**
	  * Version property of Text type. Not Empty.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Version;
};
