
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"

#include "UStartingSet.generated.h"

class UItemWithCount; // forward declaration
class UHero; // forward declaration
class ULocation; // forward declaration

/**
  * Starting Set with Integer id. Settings.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UStartingSet : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

	/**
	  * De-referenced collection of documents for Heroes. Should not be directly used.
	  */
	TMap<FString,UHero*> _heroesDocuments;
	/**
	  * De-referenced document of Location. Should not be directly used.
	  */
	ULocation* _locationDocument;
public:
	/**
	  * Id property of Integer type. Not Null, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Id;
	/**
	  * Items property of Document Collection type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<int32,UItemWithCount*> Items;
	/**
	  * Heroes property of Reference Collection type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	TMap<FString,UHero*> GetHeroes();
	/**
	  * Raw value of Heroes.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TArray<FGameDataDocumentReference> HeroesRaw;
	/**
	  * Location property of Reference type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	ULocation* GetLocation();
	/**
	  * Raw value of Location.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference LocationRaw;
};
