
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"

#include "ETrinketRarity.h"
#include "UTrinket.generated.h"

class ULocation; // forward declaration
class UHero; // forward declaration
class UItem; // forward declaration
class UParameterValue; // forward declaration

/**
  * Trinkets with Text id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UTrinket : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

	/**
	  * De-referenced document of OriginDungeon. Should not be directly used.
	  */
	ULocation* _originDungeonDocument;
	/**
	  * De-referenced document of HeroRestriction. Should not be directly used.
	  */
	UHero* _heroRestrictionDocument;
public:
	/**
	  * Id property of Text type. Not Empty, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Id;
	/**
	  * Rarity property of Pick List type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	ETrinketRarity Rarity;
	/**
	  * Origin Dungeon property of Reference type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	ULocation* GetOriginDungeon();
	/**
	  * Raw value of OriginDungeon.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference OriginDungeonRaw;
	/**
	  * Hero Restriction property of Reference type. Can Be Null.
	  */
	UFUNCTION(BlueprintCallable)
	UHero* GetHeroRestriction();
	/**
	  * Raw value of HeroRestriction.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FGameDataDocumentReference HeroRestrictionRaw;
	/**
	  * Item property of Document type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	UItem* Item;
	/**
	  * Effects property of Document Collection type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TMap<int32,UParameterValue*> Effects;
};
