
#pragma once
//
// The source code was generated by the Charon, GameDevWare, 2024
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

#include "GameData/UGameDataDocument.h"
#include "GameData/FGameDataDocumentReference.h"
#include "GameData/FLocalizedText.h"

#include "UWeapon.generated.h"


/**
  * Weapon1 with Text id.
  */
UCLASS(BlueprintType)
class RPGGAMEDATA_API UWeapon : public UGameDataDocument
{
	GENERATED_BODY()

public:
    static const FString SchemaId;
    static const FString SchemaName;

public:
	/**
	  * Id property of Text type. Not Empty, Unique.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FString Id;
	/**
	  * Name property of Localized Text type. Not Null.
	  */
	UFUNCTION(BlueprintCallable)
	FText GetName();
	/**
	  * Raw value of Name.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FLocalizedText NameRaw;
	/**
	  * Damage From property of Integer type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 DamageFrom;
	/**
	  * Damage To property of Integer type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 DamageTo;
	/**
	  * from 0.0 to 1.0 where 0.5 is 50%. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	float CriticalStrikeChance;
	/**
	  * Speed property of Integer type. Not Null.
	  */
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	int32 Speed;
};
